/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	read names header file for CIP MACHINE mLampUnit
	Filename: INTF_ReadNames.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_ReadNames__)
    #define __INTF_ReadNames__

namespace lampunit
{
	namespace cipmachine
	{
        
		/** 
		* class INTF_ReadNames
		* names of local channel messages
		*/
		class INTF_ReadNames
		{
		public: 

			enum E_Reads
			{
				_none_ = 0 
			};
            
			/** consructors / destructors */
			INTF_ReadNames(void){}
			virtual ~INTF_ReadNames(void){}

		private: 
            
			/** prohibitted default functions */
			INTF_ReadNames(const INTF_ReadNames&);
			INTF_ReadNames& operator=(const INTF_ReadNames&);

		}; // class INTF_ReadNames

	} // namespace cipmachine
} // namespace lampunit

#endif // __INTF_ReadNames__

/*********************************************************************
    End of read names header for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[92d57fc7-08cd-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,RfBgAVJ4jerdVoJfEm7xt5QasyU=] */
