/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	local queue data header file for CIP MACHINE mLampUnit
	Filename: LOCAL_QueueData.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__LOCAL_QueueData__)
    #define __LOCAL_QueueData__


namespace lampunit
{
	namespace cipmachine
	{
		union LOCAL_QueueData
		{
		};

	} // namespace cipmachine
} // namespace lampunit

#endif // __LOCAL_QueueData__

/*********************************************************************
    End of local queue data header for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[8e94d6c6-08d2-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,ilyCrA1Qtc91sbSE+m9EqrkmO8s=] */
