/*******************************************************************
        SYSTEM U2_LiftWithAlarmMode
        Module for PROCESS Button
        Filename: Button.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LiftUnit 
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mLiftUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Button.write_access_
#define STATUS (pStatus_Button->read_access_)
#define TIME time_LiftUnit

/* Process Enumerations */

enum eMODES_Button
	{normal = 1};

enum eSTATES_Button
	{always = 1};


/* External Declarations */

extern unsigned char time_LiftUnit;
extern struct tCHNOUT_mLiftUnit CHNOUT_mLiftUnit;
int fPULSE_LiftCar (enum eOUTPLS_LiftUnit name_);

/* Global Declarations */

union tSTATUS_Button status_Button;
const union tSTATUS_Button *pStatus_Button = &status_Button;

/* Function Prototypes */

void fIMSG_C1_push(void);
void fINIT_Button (void);

/* Input Channel Functions */

void fIMSG_C1_push(void)
{
	switch(status_Button.read_access_.STATE)
	{
	case always:
	 	status_Button.write_access_.STATE = always;
	 	fPULSE_LiftCar (O6_push);
		break;
	default:
		return;
	}
	return;
}
		
/* Process Initialization Function */

void fINIT_Button (void)
{
	status_Button.write_access_.STATE = always;
}		

/*********************************************************************
	End of Module for PROCESS Button
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,f47d8c9c-37d0-11e2-9d61-05c638030bc3,75706e22-2ffd-11e2-8ce2-c76b5b13ae26,f8d9e1eb-37d0-11e2-9d61-05c638030bc3,f47fd690-37d0-11e2-9d61-05c638030bc3,75706e25-2ffd-11e2-8ce2-c76b5b13ae26,75706e57-2ffd-11e2-8ce2-c76b5b13ae26,fKcmGC65SZ8nUGlwdszrWT2+4RM=] */
