/*********************************************************************
	SYSTEM U2_LiftWithAlarmMode
	IMPLEMENTATION Lift
	Error Header File for CIP MACHINE mLiftUnit
	Filename: eLiftUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftUnit 
		'unsigned char' for delays
*********************************************************************/

#if !defined(_eLiftUnit_hLiftUnit_)
	#define _eLiftUnit_hLiftUnit_

/* Include Files */

#include "mLiftUnit.h"

#endif // _eLiftUnit_hLiftUnit_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLiftUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,f47d8c9c-37d0-11e2-9d61-05c638030bc3,75706e22-2ffd-11e2-8ce2-c76b5b13ae26,f8d9e1eb-37d0-11e2-9d61-05c638030bc3,f47fd690-37d0-11e2-9d61-05c638030bc3,23yz9Rv81krlG+SMJkct1qKckDA=] */
