/*********************************************************************
	SYSTEM U2_LiftWithAlarmMode
	IMPLEMENTATION Lift
	Module for CIP SHELL sLiftUnit
	Filename: sLiftUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftUnit 
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "sLiftUnit.h"

/* Input Interface */

struct tIN_LiftUnit IN_LiftUnit;

/* Output Interface */

struct tOUT_LiftUnit OUT_LiftUnit;

/* Trigger Interface */

struct tTRG_LiftUnit TRG_LiftUnit;

/*********************************************************************
	End of Module for CIP SHELL sLiftUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,f47d8c9c-37d0-11e2-9d61-05c638030bc3,75706e22-2ffd-11e2-8ce2-c76b5b13ae26,f8d9e1eb-37d0-11e2-9d61-05c638030bc3,f47fd690-37d0-11e2-9d61-05c638030bc3,f47fd695-37d0-11e2-9d61-05c638030bc3,BkJyoe/zZIHWHCB7qnn4c/tPA9c=] */
