/*********************************************************************
	SYSTEM U2_LiftWithAlarmMode
	IMPLEMENTATION  Lift
	Trace Interface Header File for CIP MACHINE mLiftUnit
	Filename: tLiftUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftUnit 
		'unsigned char' for delays
*********************************************************************/

#if !defined(_tLiftUnit_hLiftUnit_)
	#define _tLiftUnit_hLiftUnit_

/* Include Files */

#include "mLiftUnit.h"

#endif // _tLiftUnit_hLiftUnit_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLiftUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,f47d8c9c-37d0-11e2-9d61-05c638030bc3,75706e22-2ffd-11e2-8ce2-c76b5b13ae26,f8d9e1eb-37d0-11e2-9d61-05c638030bc3,f47fd690-37d0-11e2-9d61-05c638030bc3,BN9IAZJoLswT7pmgN6nZuXlkhD4=] */
