/*********************************************************************
	SYSTEM U2_LiftWithAlarmMode
	IMPLEMENTATION Lift
	Trace Interface Module for CIP MACHINE mLiftUnit
	Filename: tLiftUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftUnit 
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "tLiftUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLiftUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,f47d8c9c-37d0-11e2-9d61-05c638030bc3,75706e22-2ffd-11e2-8ce2-c76b5b13ae26,f8d9e1eb-37d0-11e2-9d61-05c638030bc3,f47fd690-37d0-11e2-9d61-05c638030bc3,L9mbSj8hp4F8ednxc4loEBir8d0=] */
