/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION  LampImpl
	Trace Interface Header File for CIP MACHINE mLampUnit
	Filename: tLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_tLampUnit_hLampUnit_HANS_)
	#define _tLampUnit_hLampUnit_HANS_

/* Include Files */

#include "mLampUnit.h"

#endif // _tLampUnit_hLampUnit_HANS_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,7848c712-b785-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,7848c72b-b785-11ea-9e22-1112d6355503,7848c710-b785-11ea-9e22-1112d6355503,OXzxfEysULa0fAWffyx6Chr9Hpg=] */
