/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	shell header file for CIP SHELL sTemplateUnit
	Filename: CIPS_sTemplateUnit.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__CIPS_sTemplateUnit__)
    #define __CIPS_sTemplateUnit__

/* Begin Protected Region [[include]] */

/* End Protected Region   [[include]] */




#include <stdio.h>

namespace templateunit
{
	namespace cipshell
	{

	} // namespace cipshell
} // namespace templateunit

#endif // __CIPS_sTemplateUnit__

/*********************************************************************
    End of shell header for CIP SHELL sTemplateUnit
*********************************************************************/
/* Actifsource ID=[ec7f2727-08dc-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,exbykBtrrDrruenIP2mhhEIzonI=] */
