/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	cip machine factory header file for CIP SHELL sTemplateUnit
	Filename: FCTY_mTemplateUnit.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__FCTY_mTemplateUnit__)
    #define __FCTY_mTemplateUnit__

#include "INTF_ActionMessagePort.hpp"
#include "INTF_mTemplateUnit.hpp"

namespace templateunit
{

	namespace cipshell
	{
        
		/** 
		* class FCTY_mTemplateUnit
		* factory class for cip machine creation
		*/
		class FCTY_mTemplateUnit
		{
		public: 
            
			/** Creates a new CIP Machine
			* parameter: pointer to the Action Message Handler created by user
			* return: pointer to the CIP Machine*/
			static INTF_mTemplateUnit* cipmachine(INTF_ActionMessagePort* i_amp);

		private: 
            
			/** prohibitted default functions */
			FCTY_mTemplateUnit(const FCTY_mTemplateUnit&);
			FCTY_mTemplateUnit& operator=(const FCTY_mTemplateUnit&);

		}; // class FCTY_mTemplateUnit

	} // namespace cipshell
} // namespace templateunit

#endif // __FCTY_mTemplateUnit__

/*********************************************************************
    End of cip machine factory header for CIP SHELL sTemplateUnit
*********************************************************************/
/* Actifsource ID=[85bab761-0965-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,M0vW62WjMv+S3ctU2OU0JKd/gMk=] */
