/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	constants interface header file for CIP SHELL sTemplateUnit
	Filename: INTF_Constant.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_Constant__)
    #define __INTF_Constant__

namespace templateunit
{
	namespace cipshell
	{
        
		/** 
		* class INTF_Constant
		* interface defining global constants
		*/
		class INTF_Constant
		{
		public: 
            
			/** consructors / destructors */
			INTF_Constant(void){}
			virtual ~INTF_Constant(void){}

			/** integer constants */
			enum E_Constant
			{
				ddd = 55
			};          
		private: 
            
			/** prohibitted default functions */
			INTF_Constant(const INTF_Constant&);
			INTF_Constant& operator=(const INTF_Constant&);

		}; // class INTF_Constant

	} // namespace cipshell
} // namespace templateunit

#endif // __INTF_Constant__

/*********************************************************************
    End of constants interface header for CIP SHELL sTemplateUnit
*********************************************************************/
/* Actifsource ID=[007b56c0-08e6-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,nOlD58WWC7LcLW8eneKV4nKkqGc=] */
