/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	constants interface file for CIP SHELL sTemplateUnit
	Filename: INTF_Constant.cpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#include "INTF_Constant.hpp"

namespace templateunit
{
	namespace cipshell
	{
	} // namespace cipshell
} // namespace templateunit

/*********************************************************************
    End of constants interface for CIP SHELL sTemplateUnit
*********************************************************************/
/* Actifsource ID=[baaf3bef-0965-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,rJP41ADIW56pShOfi10tWW/O6zQ=] */
