/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	read names header file for CIP MACHINE mTemplateUnit
	Filename: INTF_ReadNames.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_ReadNames__)
    #define __INTF_ReadNames__

namespace templateunit
{
	namespace cipmachine
	{
        
		/** 
		* class INTF_ReadNames
		* names of local channel messages
		*/
		class INTF_ReadNames
		{
		public: 

			enum E_Reads
			{
				_none_ = 0 
			};
            
			/** consructors / destructors */
			INTF_ReadNames(void){}
			virtual ~INTF_ReadNames(void){}

		private: 
            
			/** prohibitted default functions */
			INTF_ReadNames(const INTF_ReadNames&);
			INTF_ReadNames& operator=(const INTF_ReadNames&);

		}; // class INTF_ReadNames

	} // namespace cipmachine
} // namespace templateunit

#endif // __INTF_ReadNames__

/*********************************************************************
    End of read names header for CIP MACHINE mTemplateUnit
*********************************************************************/
/* Actifsource ID=[92d57fc7-08cd-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,k0TAh1Ev4ZFq6qezvZ1Zq/kXjAc=] */
