/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	abstract cip process header file for CIP MACHINE mTemplateUnit
	Filename: PROC_CipProcess.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__PROC_CipProcess__)
    #define __PROC_CipProcess__

#include "CIPS_sTemplateUnit.hpp"

namespace templateunit
{
	namespace cipmachine
	{
        
		/** 
		* class PROC_CipProcess
		* common superclass for CIP Processes
		*/
		class PROC_CipProcess
		{
		public: 
            
			/** consructors / destructors */
			PROC_CipProcess(void){}
			virtual ~PROC_CipProcess(void){}
            
			/** extension input functions */
			virtual void TIMEUP_(void){}
			virtual void CHAIN_(void){}
			virtual void AUTO_(void){}
			virtual void READ_(void){}

		protected: 
            

		private: 
            
			/** prohibitted default functions */
			PROC_CipProcess(const PROC_CipProcess&);
			PROC_CipProcess& operator=(const PROC_CipProcess&);

		}; // class PROC_CipProcess

	} // namespace cipmachine
} // namespace templateunit

#endif // __PROC_CipProcess__

/*********************************************************************
    End of abstract cip process header for CIP MACHINE mTemplateUnit
*********************************************************************/
/* Actifsource ID=[5568d3bf-0beb-11e3-b115-a3f7f19b76fe,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,aXsdeu/ZjN/KvU5EJwCsEgDDqlo=] */
