/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	cip process Lamp strings header file for PROCESS Lamp
	Filename: INTF_LampStrings.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_LampStrings__)
    #define __INTF_LampStrings__

#include "INTF_LampNames.hpp"

namespace lampunit
{

	namespace lampcluster
	{
        
		/**
		* class INTF_LampStrings
		* strings for process Lamp
		*/
		class INTF_LampStrings
		{
		public: 

			static char *stateString(INTF_LampNames::E_State i_state)
			{
				return m_stateString[i_state];
			}

			static char *modeString(INTF_LampNames::E_Mode i_mode)
			{
				return m_modeString[i_mode];
			}
            
			static char *inputString(INTF_LampNames::E_Input i_input)
			{
				return m_inputString[i_input];
			}

			static char *outpulseString(INTF_LampNames::E_Outpulse i_outpulse)
			{
				return m_outpulseString[i_outpulse];
			}

			static char *m_stateString[];
			static char *m_modeString[];
			static char *m_inputString[];
			static char *m_outpulseString[];

		private: 
            
			/** prohibitted default functions */
			INTF_LampStrings(void);
			~INTF_LampStrings(void);
			INTF_LampStrings(const INTF_LampStrings&);
			INTF_LampStrings& operator=(const INTF_LampStrings&);

		}; // class INTF_LampStrings

	} // namespace lampcluster
} // namespace lampunit

#endif // __INTF_LampStrings__

/*********************************************************************
    End of cip process Lamp strings header for PROCESS Lamp
*********************************************************************/
/* Actifsource ID=[d20641f8-0991-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,7848c70f-b785-11ea-9e22-1112d6355503,7848c705-b785-11ea-9e22-1112d6355503,eS5hOp2oYOBTsfhA6tXhQQ6leQM=] */
