/*********************************************************************
	SYSTEM CIPLIBRARY
	cip common strings header file 
	Filename: INTF_CommonStrings.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__INTF_CommonStrings__)
	#define __INTF_CommonStrings__

#include "INTF_CommonNames.hpp"

namespace ciplibrary
{
	
	/** 
	 * class INTF_CommonStrings
	 * strings corresponding to common names
	 */
	class INTF_CommonStrings
	{
	public: 

		static char * commonString(INTF_CommonNames::E_CommonNames i_commonName)
		{
			return m_commonStrings[i_commonName];
		}


		static char *m_commonStrings[];

	private: 
	}; // class INTF_CommonStrings

} // namespace ciplibrary

#endif // __INTF_CommonStrings__

/*********************************************************************
	End of cip common strings header
*********************************************************************/
/* Actifsource ID=[4a26cb3e-0965-11e3-b902-17aaca85d2fd,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,Dn2ihcY6OFBiyglsmVdNFf6iwJE=] */
