/*********************************************************************
	SYSTEM CIPLIBRARY
	cip common strings file 
	Filename: INTF_CommonStrings.cpp
	generated by CIP Tool(R) Version 5.20.00
	activated code options:
		C++ code
*********************************************************************/

#include "INTF_CommonStrings.hpp"

namespace ciplibrary
{
	
	/** static variable */
	char *INTF_CommonStrings::m_commonStrings[] = 
	{
		"               ", 		// no input
		"AUTO           ", 
		"CHAIN          ", 
		"TIMEUP         ", 
		"               ", 		// no outpulse
		"READ ", 
		"STEP ", 
		"INFO ", 
		"TIME ", 
		"               ", 		// no input
		"AUTO           ", 
		"CHAIN          ", 
		"TIMEUP         ", 
		"               ", 		// no outpulse
		"READ ", 
		"STEP ", 
		"INFO ", 
		"TIME ", 
		"  ", 
		"S ", 
		"P ", 
		"C "
	};

} // namespace ciplibrary

/*********************************************************************
	End of cip common strings
*********************************************************************/
/* Actifsource ID=[6912066b-08ad-11e3-b902-17aaca85d2fd,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,+MJFlPf9x4koMLNoltFs3Rh2qVQ=] */
