/*********************************************************************
	SYSTEM LampSystem_ETL
	IMPLEMENTATION LampImpl_c
	shell header file for CIP SHELL sLampUnit
	Filename: CIPS_sLampUnit.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__CIPS_sLampUnit__)
    #define __CIPS_sLampUnit__

/* Begin Protected Region [[include]] */

/* End Protected Region   [[include]] */




#include <stdio.h>

namespace lampunit::cipshell
{

} // namespace lampunit::cipshell

#endif // __CIPS_sLampUnit__

/*********************************************************************
    End of shell header for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[cfa5e168-cf03-11ee-91c0-c5a9ed07c9d7,d37d50e5-fb29-11ee-88af-c1ff99c74ce0,d37d50a8-fb29-11ee-88af-c1ff99c74ce0,e83fa4af-fb29-11ee-88af-c1ff99c74ce0,d37d50e4-fb29-11ee-88af-c1ff99c74ce0,d37d50e3-fb29-11ee-88af-c1ff99c74ce0,imkuIWatmh/UUU/QfUkJFYA/GXg=] */
