/*********************************************************************
	SYSTEM LampSystem_ETL
	IMPLEMENTATION LampImpl_c
	constants interface file for CIP SHELL sLampUnit
	Filename: INTF_Constant.cpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        'unsigned long' for delays
*********************************************************************/

#include "INTF_Constant.hpp"

namespace lampunit
{
	namespace cipshell
	{
	} // namespace cipshell
} // namespace lampunit

/*********************************************************************
    End of constants interface for CIP SHELL sLampUnit
*********************************************************************/

/* Actifsource ID=[cfa65642-cf03-11ee-91c0-c5a9ed07c9d7,d37d50e5-fb29-11ee-88af-c1ff99c74ce0,d37d50a8-fb29-11ee-88af-c1ff99c74ce0,e83fa4af-fb29-11ee-88af-c1ff99c74ce0,d37d50e4-fb29-11ee-88af-c1ff99c74ce0,d37d50e3-fb29-11ee-88af-c1ff99c74ce0,Hash] */
