/*********************************************************************
	SYSTEM LampSystem_ETL
	IMPLEMENTATION LampImpl_c
	cip machine interface header file for CIP SHELL sLampUnit
	Filename: INTF_mLampUnit.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        'unsigned long' for delays
*********************************************************************/
#pragma once

#include "../ciplibrary/INTF_CipMachine.hpp"

namespace lampunit::cipshell
{
     
    /** 
    * class INTF_mLampUnit
    * interface declaring input messages for cip machine
    */
    class INTF_mLampUnit : public ciplibrary::INTF_CipMachine
    {
    public: 
        
      /** constructors / destructors */
      INTF_mLampUnit(){}
      virtual ~INTF_mLampUnit(){}

      /** event message interface */
      /**
      * Triggers CIP Machine by input message Push (channel ButtonEvents).
      */
      virtual void C1_Push() = 0;
            
      /**
      * Triggers CIP Machine by input message Release (channel ButtonEvents).
      */
      virtual void C1_Release() = 0;
            
      /** 
      * global unit time
      */
      unsigned long TIME;

    private: 
            
      /** prohibitted default functions */
      INTF_mLampUnit(const INTF_mLampUnit&);
      INTF_mLampUnit& operator=(const INTF_mLampUnit&);

    }; // class INTF_mLampUnit

} // namespace lampunit::cipshell

/* Actifsource ID=[cfa658e8-cf03-11ee-91c0-c5a9ed07c9d7,d37d50e5-fb29-11ee-88af-c1ff99c74ce0,d37d50a8-fb29-11ee-88af-c1ff99c74ce0,e83fa4af-fb29-11ee-88af-c1ff99c74ce0,d37d50e4-fb29-11ee-88af-c1ff99c74ce0,d37d50e3-fb29-11ee-88af-c1ff99c74ce0,JUAdFJVgBhqTGgpNJlZ1GCHN5jA=] */
