/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	cip record header file for CIP RECORD recType
	Filename: CREC_recType.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__CREC_recType__)
    #define __CREC_recType__

#include <iostream>
#include <cstdarg>
#include "CIPS_sLampUnit.hpp"

namespace lampunit
{
    namespace cipshell
    {
        
        /** 
         * class CREC_recType
         * cip record recType
         */
        struct CREC_recType
        {
            float field1;       
            

            /** member access functions */   
            const float getField1(void) const;
            void setField1(const float  i_field1);

        }; // struct CREC_recType

    } // namespace cipshell
} // namespace lampunit

#endif // __CREC_recType__

/*********************************************************************
    End of cip record header for CIP RECORD recType
*********************************************************************/
/* Actifsource ID=[43b08024-096e-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,7848c715-b785-11ea-9e22-1112d6355503,2lsS7IZKZwTm+KOIqfsTCMwdbeo=] */
