/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	cip machine factory header file for CIP SHELL sLampUnit
	Filename: FCTY_mLampUnit.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__FCTY_mLampUnit__)
    #define __FCTY_mLampUnit__

#include "INTF_ActionMessagePort.hpp"
#include "INTF_ErrorHandler.hpp"
#include "INTF_mLampUnit.hpp"

namespace lampunit
{

	namespace cipshell
	{
        
		/** 
		* class FCTY_mLampUnit
		* factory class for cip machine creation
		*/
		class FCTY_mLampUnit
		{
		public: 
            
			/** Creates a new CIP Machine
			* parameter: pointer to the Action Message Handler created by user
			* parameter: pointer to the Error Function Handler created by user
			* return: pointer to the CIP Machine*/
			static INTF_mLampUnit* cipmachine(INTF_ActionMessagePort* i_amp,
				ciplibrary::INTF_ErrorHandler<char >* i_ehd);

		private: 
            
			/** prohibitted default functions */
			FCTY_mLampUnit(const FCTY_mLampUnit&);
			FCTY_mLampUnit& operator=(const FCTY_mLampUnit&);

		}; // class FCTY_mLampUnit

	} // namespace cipshell
} // namespace lampunit

#endif // __FCTY_mLampUnit__

/*********************************************************************
    End of cip machine factory header for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[85bab761-0965-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,ZRP3guZD5oLy/XAE4bfL3MLbdmQ=] */
