/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	constants interface header file for CIP SHELL sLampUnit
	Filename: INTF_Constant.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_Constant__)
    #define __INTF_Constant__

namespace lampunit
{
	namespace cipshell
	{
        
		/** 
		* class INTF_Constant
		* interface defining global constants
		*/
		class INTF_Constant
		{
		public: 
            
			/** consructors / destructors */
			INTF_Constant(void){}
			virtual ~INTF_Constant(void){}

		private: 
            
			/** prohibitted default functions */
			INTF_Constant(const INTF_Constant&);
			INTF_Constant& operator=(const INTF_Constant&);

		}; // class INTF_Constant

	} // namespace cipshell
} // namespace lampunit

#endif // __INTF_Constant__

/*********************************************************************
    End of constants interface header for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[007b56c0-08e6-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,cHXZJPJjoRuLEnTH2NEEWnyDEMM=] */
