/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	usertypes header file for CIP SHELL sLampUnit
	Filename: INTF_usertypes.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_usertypes__)
    #define __INTF_usertypes__

#include "CIPS_sLampUnit.hpp"
#include "INTF_Constant.hpp"
/* Begin Protected Region [[include]] */

/* End Protected Region   [[include]] */

/* Text Switch Constants */

namespace lampunit
{
	namespace cipshell
	{
        
		/** user types */
		//usetTypeTest
		

	} // namespace cipshell
} // namespace lampunit

#endif // __INTF_usertypes__

/*********************************************************************
    End of usertypes header for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[e49bc7d1-0968-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,6qwGmHGFvm2Vjgi6ugxxtZMlqOU=] */
