/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_cpp
	constants interface file for CIP SHELL sLampUnit
	Filename: INTF_Constant.cpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        call context error function
	        'unsigned long' for delays
*********************************************************************/

#include "INTF_Constant.hpp"

namespace lampunit
{
	namespace cipshell
	{
	} // namespace cipshell
} // namespace lampunit

/*********************************************************************
    End of constants interface for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[baaf3bef-0965-11e3-b902-17aaca85d2fd,242979e4-b786-11ea-9e22-1112d6355503,7848c6d5-b785-11ea-9e22-1112d6355503,06ed7fd9-b786-11ea-9e22-1112d6355503,242979e3-b786-11ea-9e22-1112d6355503,242979e2-b786-11ea-9e22-1112d6355503,F3mHYGE++APnyPztY70PwnwTE/A=] */
