/*******************************************************************
        SYSTEM ChairArray
        Module for PROCESS ButtonHardener
        Filename: ButtonHardener.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use channel interface
        		naming option: use default prefix
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mChairUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define ID (*id_)
#define SELF (*self_)
#define STATUS (pStatus_ButtonHardener->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_ButtonHardener
	{normal = 1};

enum eSTATES_ButtonHardener
	{pushed = 1, released};


/* External Declarations */

extern unsigned long time_;
extern struct tCHNOUT_mChairUnit CHNOUT_mChairUnit;
int fPULSE_PassengersControl (enum eOUTPLS_ name_,
  struct tID_PassengersControl *procid_);

/* Global Declarations */

union tSTATUS_ButtonHardener status_ButtonHardener;
const union tSTATUS_ButtonHardener *pStatus_ButtonHardener = &status_ButtonHardener;
static struct tPRSTAT_ButtonHardener *self_;
static struct tID_ButtonHardener currentid_;
static const struct tID_ButtonHardener *id_ = &currentid_;

/* Function Prototypes */

void fICHAN_Evt_ButtonHardener (enum eMSG_Evt_ButtonHardener name_,
   struct tID_Evt_ButtonHardener *chanid_);
void fINIT_ButtonHardener (void);

/* Multiple Cast Functions */

static void fCAST_PassengersControl(enum eOUTPLS_ name_,
   struct tID_ButtonHardener *txid_)
{
	struct tID_PassengersControl ID_PassengersControl;
	ID_PassengersControl.cushionIndex = txid_->cushionIndex;
	switch(name_)
	{	
	case O4_push:
	case O4_release:
		fPULSE_PassengersControl(name_, &ID_PassengersControl);
		break;
	default: 
		break;
	}
}	
/* Input Channel Functions */

void fICHAN_Evt_ButtonHardener(enum eMSG_Evt_ButtonHardener name_,
   struct tID_Evt_ButtonHardener *chanid_)
{
	struct tID_ButtonHardener ID_ButtonHardener;
	int invalid_index_;
	if ((invalid_index_ = chanid_->cushionIndex) < 0 || chanid_->cushionIndex >= CUSHION_COUNT )
	{
		return;
	}
	currentid_.cushionIndex = chanid_->cushionIndex;
	ID_ButtonHardener.cushionIndex = chanid_->cushionIndex;
	self_ = &status_ButtonHardener.write_access_[currentid_.cushionIndex];
	switch(name_)
	{
		/* MESSAGE Push of INPORT ButtonHardener */
	case C1_Push:
		switch(status_ButtonHardener.read_access_[currentid_.cushionIndex].STATE)
		{
		case released:
		 	status_ButtonHardener.write_access_[currentid_.cushionIndex].STATE = pushed;
		 	fCAST_PassengersControl (O4_push, &ID_ButtonHardener);
			break;
		default:
			return;
		}		
		break;
		/* MESSAGE Release of INPORT ButtonHardener */
	case C1_Release:
		switch(status_ButtonHardener.read_access_[currentid_.cushionIndex].STATE)
		{
		case pushed:
		 	status_ButtonHardener.write_access_[currentid_.cushionIndex].STATE = released;
		 	fCAST_PassengersControl (O4_release, &ID_ButtonHardener);
			break;
		default:
			return;
		}		
		break;
	default:
		return;
	}
	return;
}
		
/* Process Initialization Function */

void fINIT_ButtonHardener (void)
{
	int LOCAL_cushionIndex;
	for (LOCAL_cushionIndex = 0; LOCAL_cushionIndex < CUSHION_COUNT; LOCAL_cushionIndex++)
	{
		status_ButtonHardener.write_access_[LOCAL_cushionIndex].STATE = released;
	}
}		

/*********************************************************************
	End of Module for PROCESS ButtonHardener
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,2e7be38b-c77a-11ea-9e9f-c1d3048691bc,2e797237-c77a-11ea-9e9f-c1d3048691bc,2e7be3c2-c77a-11ea-9e9f-c1d3048691bc,2e7be389-c77a-11ea-9e9f-c1d3048691bc,2e7be388-c77a-11ea-9e9f-c1d3048691bc,2e79727e-c77a-11ea-9e9f-c1d3048691bc,tp5wWvKAK+AL5FKalfhFeozx0oo=] */
