/*********************************************************************
	SYSTEM ChairArray
	IMPLEMENTATION ChairImplementation
	Error Interface Module for CIP MACHINE mChairUnit
	Filename: eChairUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "eChairUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mChairUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,2e7be38b-c77a-11ea-9e9f-c1d3048691bc,2e797237-c77a-11ea-9e9f-c1d3048691bc,2e7be3c2-c77a-11ea-9e9f-c1d3048691bc,2e7be389-c77a-11ea-9e9f-c1d3048691bc,QL3HovFL8/4PDgPyBCDw0KWD/oU=] */
