/*********************************************************************
	SYSTEM ChairArray
	IMPLEMENTATION ChairImplementation
	Module for CIP MACHINE mChairUnit
	Filename: mChairUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mChairUnit.h"

/* External Declarations */

void fICHAN_Evt_ButtonHardener (enum eMSG_Evt_ButtonHardener name_,
   struct tID_Evt_ButtonHardener *chanid_);
void fICHAN_Evt_ButtonSofter (enum eMSG_Evt_ButtonSofter name_,
   struct tID_Evt_ButtonSofter *chanid_);
void fICHAN_Evt_Pressure (enum eMSG_Evt_Pressure name_,
   union tDATA_Evt_Pressure *data_,
   struct tID_Evt_Pressure *chanid_);
void fINIT_AllButtonHardener (void);
void fINIT_AllButtonSoftener (void);
void fINIT_ButtonHardener (void);
void fINIT_ButtonSoftener (void);
void fINIT_PassengersControl (void);
void fINIT_Pressure (void);
void fINIT_PressureControl (void);
void fINIT_Proxy (void);
void fINIT_Pump (void);
void fINIT_PumpControl (void);
void fINIT_Valve (void);

/* Global Declarations */

unsigned long time_ = 0;
struct tCHNOUT_mChairUnit CHNOUT_mChairUnit;
struct tTIMING_mChairUnit TIMING_mChairUnit[2];
struct tCHNING_mChairUnit CHNING_mChairUnit;
struct tTMQE_mChairUnit *tuhead_mChairUnit, *tutail_mChairUnit, *chhead_mChairUnit, *chtail_mChairUnit;

/* Function Prototypes */

void fSETTIM_mChairUnit (unsigned long *delay_, struct tTMEL_mChairUnit *timer_, struct tTMQE_mChairUnit *timeup_);
void fSTOPTIM_mChairUnit (struct tTMEL_mChairUnit *timer_, struct tTMQE_mChairUnit *timeup_);
void fSETCHN_mChairUnit (struct tTMQE_mChairUnit *chain_);
void fSTEP_(void);
void fCHAIN_(void);
void fTIMEUP_(void);
void fREAD_(void);

/* AUTO_ Handler Function */

static void fAUTOHDL_(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_(void)
{
	int i_;
	++time_;
	for (i_ = 0; i_ < 2; i_ ++)
	{
		if (TIMING_mChairUnit[i_].set_)
		{
			TIMING_mChairUnit[i_].tkhndl_();
		}
	}
}

void fSETTIM_mChairUnit (unsigned long *delay_, struct tTMEL_mChairUnit *timer_, struct tTMQE_mChairUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (!timer_->set_)
		{
			++TIMING_mChairUnit[timeup_->proctype_].set_;
		}
		timer_->set_ = TRUE;
		timer_->end_ = time_ + *delay_;
		if (tuhead_mChairUnit == timeup_)
		{
			tuhead_mChairUnit = tuhead_mChairUnit->next_;
		}
		if (timeup_->preced_)
		{
			timeup_->preced_->next_ = timeup_->next_;
		}
		if (timeup_->next_)
		{
			timeup_->next_->preced_ = timeup_->preced_;
		}
		if (tutail_mChairUnit == timeup_)
		{
			tutail_mChairUnit = timeup_->preced_;
		}
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
		{
			--TIMING_mChairUnit[timeup_->proctype_].set_;
		}
		timer_->set_ = FALSE;
		if (tuhead_mChairUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (!tuhead_mChairUnit)
			{
				tuhead_mChairUnit = tutail_mChairUnit = timeup_;
			}
			else 
			{
				tutail_mChairUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mChairUnit;
				tutail_mChairUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mChairUnit (struct tTMEL_mChairUnit *timer_, struct tTMQE_mChairUnit *timeup_)
{
	if (timer_->set_)
	{
		--TIMING_mChairUnit[timeup_->proctype_].set_;
	}
	timer_->set_ = FALSE;
	if (tuhead_mChairUnit == timeup_)
	{
		tuhead_mChairUnit = tuhead_mChairUnit->next_;
	}
	if (timeup_->preced_)
	{
		timeup_->preced_->next_ = timeup_->next_;
	}
	if (timeup_->next_)
	{
		timeup_->next_->preced_ = timeup_->preced_;
	}
	if (tutail_mChairUnit == timeup_)
	{
		tutail_mChairUnit = timeup_->preced_;
	}
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

void fSETCHN_mChairUnit (struct tTMQE_mChairUnit *chain_)
{
	if (chhead_mChairUnit != chain_ && !chain_->preced_ && !chain_->next_)
	{
		if (!chhead_mChairUnit)
		{
			chhead_mChairUnit = chtail_mChairUnit = chain_;
		}
		else 
		{
			chtail_mChairUnit->next_ = chain_;
			chain_->preced_ = chtail_mChairUnit;
			chtail_mChairUnit = chain_;
		}
	}
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_(void)
{
	if (chhead_mChairUnit != 0)
	{
		CHNING_mChairUnit.chhndl_();
	}
	else if (tuhead_mChairUnit != 0)
	{
		TIMING_mChairUnit[tuhead_mChairUnit->proctype_].tuhndl_();
	}
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_(void)
{
	if (chhead_mChairUnit != 0)
	{
		CHNING_mChairUnit.chhndl_();
	}
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_(void)
{
	if (tuhead_mChairUnit != 0)
	{
		TIMING_mChairUnit[tuhead_mChairUnit->proctype_].tuhndl_();
	}
	return;
}

	/* Read Function for CIP Machine */

void fREAD_(void)
{
	return;
}


/* Initialization Function */

int fINIT_(void)
{
	tuhead_mChairUnit = tutail_mChairUnit = 0;
	chhead_mChairUnit = chtail_mChairUnit = 0;
	TRG_.TICK_ = fTICK_;
	TRG_.CHAIN_ = fCHAIN_;
	TRG_.TIMEUP_ = fTIMEUP_;
	TRG_.STEP_ = fSTEP_;
	TRG_.READ_ = fREAD_;
	TRG_.AUTO_ = fAUTOHDL_;
	IN_.Evt_ButtonHardener = fICHAN_Evt_ButtonHardener;
	IN_.Evt_ButtonSofter = fICHAN_Evt_ButtonSofter;
	IN_.Evt_Pressure = fICHAN_Evt_Pressure;
	iCHAN_();
	if (!OUT_.Act_Pump)
	{
		return 0;
	}
	fINIT_AllButtonHardener ();
	fINIT_AllButtonSoftener ();
	fINIT_ButtonHardener ();
	fINIT_ButtonSoftener ();
	fINIT_PassengersControl ();
	fINIT_Pressure ();
	fINIT_PressureControl ();
	fINIT_Proxy ();
	fINIT_Pump ();
	fINIT_PumpControl ();
	fINIT_Valve ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mChairUnit
*********************************************************************/

/* Actifsource ID=[a9fcef86-9d17-11e1-90e4-e1fd5739c0f6,2e7be38b-c77a-11ea-9e9f-c1d3048691bc,2e797237-c77a-11ea-9e9f-c1d3048691bc,2e7be3c2-c77a-11ea-9e9f-c1d3048691bc,2e7be38a-c77a-11ea-9e9f-c1d3048691bc,2e7be389-c77a-11ea-9e9f-c1d3048691bc,vxYdAlKeo2zcaNfctI4BH2u6SnY=] */
