/*******************************************************************
        SYSTEM ChairArray
        Module for PROCESS PassengersControl
        Filename: PassengersControl.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use channel interface
        		naming option: use default prefix
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mChairUnit.h"

/* Process Macro Definitions */

#define ID (*id_)
#define SELF (*self_)
#define STATUS (pStatus_PassengersControl->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_PassengersControl
	{normalPressure = 1, maxPressure = 5, minPressure = 6};

enum eSTATES_PassengersControl
	{evacuate = 1, filling, standby};

enum eINPULS_PassengersControl
	{IP_pushHardener = 1, IP_releaseHardener = 2, IP_pushSofter = 3, 
	 IP_releaseSofter = 4, IP_maxPressure = 5, IP_minPressure = 6};
	

/* External Declarations */

extern unsigned long time_;
extern struct tCHNOUT_mChairUnit CHNOUT_mChairUnit;
extern union tSTATUS_Pressure status_Pressure;
int fPULSE_Proxy (enum eOUTPLS_ name_,
  struct tID_Proxy *procid_);

/* Global Declarations */

union tSTATUS_PassengersControl status_PassengersControl;
const union tSTATUS_PassengersControl *pStatus_PassengersControl = &status_PassengersControl;
static struct tPRSTAT_PassengersControl *self_;
static struct tID_PassengersControl currentid_;
static const struct tID_PassengersControl *id_ = &currentid_;
const int MODTAB_PassengersControl[3] =       /* [Pressure states] */
	{maxPressure, minPressure, normalPressure};


/* Function Prototypes */

int fPULSE_PassengersControl (enum eOUTPLS_ name_,
   struct tID_PassengersControl *procid_);
void fINIT_PassengersControl (void);

/* Multiple Cast Functions */

static void fCAST_Proxy(enum eOUTPLS_ name_,
   struct tID_PassengersControl *txid_)
{
	struct tID_Proxy ID_Proxy;
	ID_Proxy.cushionIndex = txid_->cushionIndex;
	switch(name_)
	{	
	case O3_evac:
	case O3_fill:
	case O3_stop:
		fPULSE_Proxy(name_, &ID_Proxy);
		break;
	default: 
		break;
	}
}	
/* Input Channel Functions */

int fPULSE_PassengersControl (enum eOUTPLS_ name_,
   struct tID_PassengersControl *procid_)
{
	struct tID_PassengersControl ID_PassengersControl;
	currentid_ = *procid_;
	ID_PassengersControl = *procid_;
	self_ = &status_PassengersControl.write_access_[currentid_.cushionIndex];
	switch(name_)
	{
		/* INPULSE maxPressure */
	case O2_maxPressure:		/* PULSE CAST from PROCESS Pressure */
		switch(MODTAB_PassengersControl[status_Pressure.read_access_[currentid_.cushionIndex].STATE - 1])
		{
		case maxPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case filling:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = standby;
				fCAST_Proxy (O3_stop, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		default:
			break;
		}
		break;
		/* INPULSE minPressure */
	case O2_minPressure:		/* PULSE CAST from PROCESS Pressure */
		switch(MODTAB_PassengersControl[status_Pressure.read_access_[currentid_.cushionIndex].STATE - 1])
		{
		case minPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case evacuate:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = standby;
				fCAST_Proxy (O3_stop, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		default:
			break;
		}
		break;
		/* INPULSE pushHardener */
	case O11_push:		/* PULSE CAST from PROCESS AllButtonHardener */
	case O4_push:		/* PULSE CAST from PROCESS ButtonHardener */
		switch(MODTAB_PassengersControl[status_Pressure.read_access_[currentid_.cushionIndex].STATE - 1])
		{
		case minPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case standby:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = filling;
				fCAST_Proxy (O3_fill, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		case normalPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case standby:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = filling;
				fCAST_Proxy (O3_fill, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		default:
			break;
		}
		break;
		/* INPULSE pushSofter */
	case O12_push:		/* PULSE CAST from PROCESS AllButtonSoftener */
	case O5_push:		/* PULSE CAST from PROCESS ButtonSoftener */
		switch(MODTAB_PassengersControl[status_Pressure.read_access_[currentid_.cushionIndex].STATE - 1])
		{
		case maxPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case standby:
				{
					/* OPERATIONS before writing */
					/* test */
					{oooo }
					status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = evacuate;
					fCAST_Proxy (O3_evac, &ID_PassengersControl);
				}
				break;
			default:
				break;
			}
			break;
		case normalPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case standby:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = evacuate;
				fCAST_Proxy (O3_evac, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		default:
			break;
		}
		break;
		/* INPULSE releaseHardener */
	case O11_released:		/* PULSE CAST from PROCESS AllButtonHardener */
	case O4_release:		/* PULSE CAST from PROCESS ButtonHardener */
		switch(MODTAB_PassengersControl[status_Pressure.read_access_[currentid_.cushionIndex].STATE - 1])
		{
		case minPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case filling:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = standby;
				fCAST_Proxy (O3_stop, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		case normalPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case filling:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = standby;
				fCAST_Proxy (O3_stop, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		default:
			break;
		}
		break;
		/* INPULSE releaseSofter */
	case O12_released:		/* PULSE CAST from PROCESS AllButtonSoftener */
	case O5_release:		/* PULSE CAST from PROCESS ButtonSoftener */
		switch(MODTAB_PassengersControl[status_Pressure.read_access_[currentid_.cushionIndex].STATE - 1])
		{
		case maxPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case evacuate:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = standby;
				fCAST_Proxy (O3_stop, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		case normalPressure:
			switch(status_PassengersControl.read_access_[currentid_.cushionIndex].STATE)
			{
			case evacuate:
				status_PassengersControl.write_access_[currentid_.cushionIndex].STATE = standby;
				fCAST_Proxy (O3_stop, &ID_PassengersControl);
				break;
			default:
				break;
			}
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_PassengersControl (void)
{
	int LOCAL_cushionIndex;
	for (LOCAL_cushionIndex = 0; LOCAL_cushionIndex < CUSHION_COUNT; LOCAL_cushionIndex++)
	{
		status_PassengersControl.write_access_[LOCAL_cushionIndex].STATE = standby;
	}
}		

/*********************************************************************
	End of Module for PROCESS PassengersControl
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,2e7be38b-c77a-11ea-9e9f-c1d3048691bc,2e797237-c77a-11ea-9e9f-c1d3048691bc,2e7be3c2-c77a-11ea-9e9f-c1d3048691bc,2e7be389-c77a-11ea-9e9f-c1d3048691bc,2e7be388-c77a-11ea-9e9f-c1d3048691bc,2e7972d0-c77a-11ea-9e9f-c1d3048691bc,0TKhWp9Se6g9neuGWmzpcpH0DDw=] */
