/*********************************************************************
	SYSTEM ChairArray
	IMPLEMENTATION  ChairImplementation
	Trace Interface Header File for CIP MACHINE mChairUnit
	Filename: tChairUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_tChairUnit_h_)
	#define _tChairUnit_h_

/* Include Files */

#include "mChairUnit.h"

#endif // _tChairUnit_h_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mChairUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,2e7be38b-c77a-11ea-9e9f-c1d3048691bc,2e797237-c77a-11ea-9e9f-c1d3048691bc,2e7be3c2-c77a-11ea-9e9f-c1d3048691bc,2e7be389-c77a-11ea-9e9f-c1d3048691bc,gB3p4RJ3IGAvvx1UGEE85ZxEXqs=] */
