/*********************************************************************
	SYSTEM ChairArray
	IMPLEMENTATION ChairImplementation
	Trace Interface Module for CIP MACHINE mChairUnit
	Filename: tChairUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "tChairUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mChairUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,2e7be38b-c77a-11ea-9e9f-c1d3048691bc,2e797237-c77a-11ea-9e9f-c1d3048691bc,2e7be3c2-c77a-11ea-9e9f-c1d3048691bc,2e7be389-c77a-11ea-9e9f-c1d3048691bc,Tz/kaGYHS4cCg0HspTWteE5Dtzc=] */
