/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_c
	Error Header File for CIP MACHINE mLampUnit
	Filename: eLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_eLampUnit_hLampUnit_HANS_)
	#define _eLampUnit_hLampUnit_HANS_

/* Include Files */

#include "mLampUnit.h"

#endif // _eLampUnit_hLampUnit_HANS_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,6f9fef7b-f5a7-11ee-8944-afc67c286a4c,6f9fc82e-f5a7-11ee-8944-afc67c286a4c,6f9fef98-f5a7-11ee-8944-afc67c286a4c,6f9fef79-f5a7-11ee-8944-afc67c286a4c,A03VJrWlGM7wjamNzzqEeCnrNw8=] */
