/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION  LampImpl_c
	Trace Interface Header File for CIP MACHINE mLampUnit
	Filename: tLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_tLampUnit_hLampUnit_HANS_)
	#define _tLampUnit_hLampUnit_HANS_

/* Include Files */

#include "mLampUnit.h"

/* Constants */

#define MAX_PROCESS_ID 2
#define MAX_MULTIPLICITY_INDEX 1
#define MAX_CHANGE_ID 7

/* Types */

struct tTRACE_DUMP_LampUnit_HANS
{
	unsigned int processId;
	unsigned int multiplicityIndex;
	int state;
	int mode;
	int modeState;
};

struct tTRACE_CHANGE_LampUnit_HANS
{
	unsigned int processId;
	unsigned int multiplicityIndex;
	int changeId;
};

/* Trace Function */

void fTRACE_APPEND_DUMP_LampUnit_HANS(struct tTRACE_DUMP_LampUnit_HANS *element, unsigned int processId, unsigned int multiplicityIndex, int mode, int state, int modeState);
void fTRACE_APPEND_CHANGE_LampUnit_HANS(struct tTRACE_CHANGE_LampUnit_HANS *element, unsigned int processId, unsigned int multiplicityIndex, int changeId);

/* Trace Interface Type */

struct tTRACE_LampUnit_HANS
{
	void (*DUMP_) (struct tTRACE_DUMP_LampUnit_HANS *element);	/* Pointer to User defined Dump Trace Function */
	void (*CHANGE_) (unsigned char elementCount, struct tTRACE_CHANGE_LampUnit_HANS elements[]);	/* Pointer to User defined State Change Trace Function */
};

/* Trace Interface */

extern struct tTRACE_LampUnit_HANS TRACE_LampUnit_HANS; /* Trace Interface defined in tLampUnit.c */

/* Unit Dump Function, defined in mLampUnit.c
	called by User to dump CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fDUMP_LampUnit_HANS(void);

/* User defined Initialization Function for Trace Interface 
	called by Unit Initialization Function */

void iTRACE_LampUnit_HANS(void);

#endif // _tLampUnit_hLampUnit_HANS_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,6f9fef7b-f5a7-11ee-8944-afc67c286a4c,6f9fc82e-f5a7-11ee-8944-afc67c286a4c,6f9fef98-f5a7-11ee-8944-afc67c286a4c,6f9fef79-f5a7-11ee-8944-afc67c286a4c,WVumyvuw94aE9jstog3JxboHXOY=] */
