/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImpl_c
	Trace Interface Module for CIP MACHINE mLampUnit
	Filename: tLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "tLampUnit.h"

/* Process Append Dump Trace Function */

void fTRACE_APPEND_DUMP_LampUnit_HANS(struct tTRACE_DUMP_LampUnit_HANS *element, unsigned int processId, unsigned int multiplicityIndex, int mode, int state, int modeState)
{
	element->processId = processId;
	element->multiplicityIndex = multiplicityIndex;
	element->mode = mode;
	element->state = state;
	element->modeState = modeState;
}

/* Process Append Change Trace Function */
		
void fTRACE_APPEND_CHANGE_LampUnit_HANS(struct tTRACE_CHANGE_LampUnit_HANS *element, unsigned int processId, unsigned int multiplicityIndex, int changeId)
{
	element->processId = processId;
	element->multiplicityIndex = multiplicityIndex;
	element->changeId = changeId;
}

/* Trace Interface */

struct tTRACE_LampUnit_HANS TRACE_LampUnit_HANS;

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,6f9fef7b-f5a7-11ee-8944-afc67c286a4c,6f9fc82e-f5a7-11ee-8944-afc67c286a4c,6f9fef98-f5a7-11ee-8944-afc67c286a4c,6f9fef79-f5a7-11ee-8944-afc67c286a4c,gdEOl+I1SiGwI12tt/MSbtkMueU=] */
