/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	cip process ProcessBB names interface header file for PROCESS ProcessBB
	Filename: INTF_ProcessBBNames.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_ProcessBBNames__)
    #define __INTF_ProcessBBNames__

namespace templateunit
{

	namespace clustera
	{
        
		/** 
		* class INTF_ProcessBBNames
		* enumerations for process ProcessBB
		*/
		class INTF_ProcessBBNames
		{
		public: 

			enum E_State
			{
				_no_state_ = 0,
				StateA_1 = 1,
				StateA_2 = 2,
				StateB = 3,
				StateBB = 4,
				StateC_1 = 5,
				StateC_2 = 6,
				SuperStateA_1 = 7,
				SuperStateA_2 = 8,
				SuperStateB_1 = 9,
				SuperStateB_2 = 10,
				SuperStateC_1 = 11,
				SuperStateC_2 = 12
			};

			enum E_Mode
			{
				_no_mode_ = 0, 
				normalA = 1 
			};   

			enum E_Input
			{
				_no_input_ = 0, 
				C1_msgA = 1,
				C1_msgB = 2,
				ip_InpulseA = 3,
				ip_TestInpulseB = 4
			};

			enum E_Outpulse
			{
				_no_outpulse_ = 0,
				op_OutpulseA = 1,
				op_TestOutpulseB = 2
			};
     
			enum E_StateAction
			{
				_no_stateAction_ = 0,
				EntryAction = 1,
				ExitAction = 2
			};
			
			/** constructors / destructors */
			INTF_ProcessBBNames(void){}
			virtual ~INTF_ProcessBBNames(void){}

		private: 
            
			/** prohibitted default functions */
			INTF_ProcessBBNames(const INTF_ProcessBBNames&);
			INTF_ProcessBBNames& operator=(const INTF_ProcessBBNames&);

		}; // class INTF_ProcessBBNames

	} // namespace clustera
} // namespace templateunit

#endif // __INTF_ProcessBBNames__

/*********************************************************************
    End of cip process ProcessBB names interface header for PROCESS ProcessBB
*********************************************************************/
/* Actifsource ID=[fdad66a9-0975-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,72701230-9b54-11ef-800e-630ffd8f1eac,727011f8-9b54-11ef-800e-630ffd8f1eac,038CFm4tu1eFIWMD+awBXxMx0DM=] */
