/*********************************************************************
	SYSTEM TemplateSystem
	IMPLEMENTATION Template_cpp
	cip process ProcessFinalA interface header file for PROCESS ProcessFinalA
	Filename: INTF_ProcessFinalA.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        enable mode inspection
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_ProcessFinalA__)
    #define __INTF_ProcessFinalA__


#include "PROC_CipProcess.hpp"
#include "INTF_ProcessFinalANames.hpp"

namespace templateunit
{
    
	namespace clustera
	{
        
		/** 
		* class INTF_ProcessFinalA
		* interface for process ProcessFinalA
		*/
		class INTF_ProcessFinalA : 
			public cipmachine::PROC_CipProcess
		{
		friend class PROC_ProcessFinalA;
	public: 
            
		/** constructors / destructors */
		INTF_ProcessFinalA(void) :
			cipmachine::PROC_CipProcess(),
			STATE(INTF_ProcessFinalANames::StateA_1),
			TEMP_STATE(INTF_ProcessFinalANames::StateA_1),
			MODE(INTF_ProcessFinalANames::normalA)
		{}

		virtual ~INTF_ProcessFinalA(void){}

		/** initialize the pointers to interaction processes */
		virtual void initInteraction(  
			void* i_ProcessFinalA,
			void* i_ProcessE) = 0;

		/** extension input functions */
		/** 
		* Trigger the process with inpulse CHAIN_.
		*/
		virtual void CHAIN_(void) = 0;
		
		/** pulse cast input functions */
		/** 
		* Trigger the process with inpulse InpulseA.
		*/
		virtual void BHV_InpulseA(void) = 0;
            
	    
	protected: 
 
		/** status variables */

		INTF_ProcessFinalANames::E_State STATE;
		INTF_ProcessFinalANames::E_State TEMP_STATE;
		INTF_ProcessFinalANames::E_Mode MODE;

	private: 
            
		/** prohibitted default functions */
		INTF_ProcessFinalA(const INTF_ProcessFinalA&);
		INTF_ProcessFinalA& operator=(const INTF_ProcessFinalA&);

        }; // class INTF_ProcessFinalA

    } // namespace clustera
} // namespace templateunit

#endif // __INTF_ProcessFinalA__

/*********************************************************************
    End of cip process ProcessFinalA interface header for PROCESS ProcessFinalA
*********************************************************************/
/* Actifsource ID=[e2fd58fb-0973-11e3-b902-17aaca85d2fd,7270396a-9b54-11ef-800e-630ffd8f1eac,726fc458-9b54-11ef-800e-630ffd8f1eac,7270398d-9b54-11ef-800e-630ffd8f1eac,72703969-9b54-11ef-800e-630ffd8f1eac,72703968-9b54-11ef-800e-630ffd8f1eac,72701230-9b54-11ef-800e-630ffd8f1eac,7270120b-9b54-11ef-800e-630ffd8f1eac,WJQ27OK5X6fy0Fvqcgo8JCcKRnA=] */
