/*********************************************************************
	SYSTEM CIPLIBRARY
	cip timer header file 
	Filename: CipChain.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/
#pragma once

namespace ciplibrary
{
	
/** 
 * class CipChain
 */
class CipChain
{
public: 
  
  void setChain()
  {
    m_chain_pending = true;
  }
  
  bool hasCHAIN_()
  {
    return m_chain_pending;    
  }
  
  void clearCHAIN_()
  {
    m_chain_pending = false;
  }
  
private:
  
  bool m_chain_pending { false };
  
};  
  
} // namespace ciplibrary

/* Actifsource ID=[9c87b190-db02-11ee-84fb-cb96c06bbf07,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,VTa3lbSDxwpFPK56ZwqdxEL1G2E=] */
