/*********************************************************************
	SYSTEM CIPLIBRARY
	cip timer header file 
	Filename: CipRead.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/
#pragma once

namespace ciplibrary
{
	
/** 
 * class CipAuto
 */
class CipRead
{
public: 
  
  void setAuto()
  {
    m_auto_pending = true;
  }
  
  bool hasAUTO_()
  {
    return m_auto_pending;    
  }
  
  void clearAUTO_()
  {
    m_auto_pending = false;
  }
  
private:
  
  bool m_auto_pending { false };
  
};  
  
} // namespace ciplibrary

/* Actifsource ID=[3d0ef046-df84-11ee-bfb1-57c2e038a55f,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,HESs+AcMRv5m7oneyLL3YqtLrm8=] */
