/*********************************************************************
	SYSTEM CIPLIBRARY
	cip chain header file 
	Filename: CipChain.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__CipChain__)
	#define __CipChain__


namespace ciplibrary
{
	
	/** 
	 * class CipChain
	 * chain element for chain queue
	 */
	
	template<class P >
	class CipChain
	{
	public: 
		
		/** consructors / destructors */
		explicit CipChain(P* i_process);
		CipChain(void){}
		virtual ~CipChain(void){}
		
		/** trigger the process with CHAIN_ */
		void CHAIN_(void);
		
		/** get the next CipChain element in the queue. */
		CipChain*& getNext(void) { return m_next; }


	private: 
		
		/** prohibitted default functions */
		CipChain& operator=(const CipChain&);

		
		/** member variables */
		P* m_process;
		CipChain* m_next;

	}; // class CipChain

/*********************************************************************
*********************************************************************/

	
	/** consructors / destructors */
	template<class P >
	CipChain<P >::CipChain(P* i_process) : 
		m_process(i_process), 
		m_next(0)
	{} // constructor()
	
	/** trigger the process with CHAIN_ */
	template<class P >
	void CipChain<P >::CHAIN_(void)
	{
		m_process->CHAIN_();
	} // CHAIN_()

} // namespace ciplibrary

#endif // __CipChain__

/*********************************************************************
	End of cip chain header
*********************************************************************/
/* Actifsource ID=[d4e3df2e-08ab-11e3-b902-17aaca85d2fd,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,34h6iRA1VFNsFoONUf0uOBpWKpk=] */
