/*********************************************************************
	SYSTEM CIPLIBRARY
	cip enum indexed array header file 
	Filename: CipEnumIndexedArray.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__CipEnumIndexArray__)
	#define __CipEnumIndexArray__

namespace ciplibrary
{
	
	/** 
	 * class CipEnumIndexedArray
	 * This class enables secure access to an array via enum index. 
	 */
	template <typename T, typename EnumType, unsigned int N>
	class CipEnumIndexedArray {
	private:
    		T data[N];

	public:
    		T& operator[](EnumType index) {
        		return data[static_cast<unsigned int>(index)];
    		}

    		const T& operator[](EnumType index) const {
        		return data[static_cast<unsigned int>(index)];
    		}
	};

} // namespace ciplibrary

#endif // __CipEnumIndexArray__

/*********************************************************************
	End of cip enum indexed array header
*********************************************************************/
/* Actifsource ID=[b43c4156-798a-11ef-b62f-a15ef4d8bf6b,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,Hash] */
