/*********************************************************************
	SYSTEM CIPLIBRARY
	cip error interface header file 
	Filename: INTF_DumpWriter.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__INTF_DumpWriter__)
	#define __INTF_DumpWriter__

#include <iostream>

namespace ciplibrary
{
	
	/** 
	 * class INTF_DumpWriter
	 * interface to dump writer 
	 */
	template<class c> class INTF_DumpWriter() {
	  public:
	    virtual ~INTF_DumpWriter(){}
	    
	    virtual void writeMachineDump(const c* i_pMachine)=0;
	    virtual void writeProcessDump(const c* i_pProcess,
	                                  const c* i_pMode,
	                                  const c* i_pState)=0;
	};

} // namespace ciplibrary

#endif // __INTF_DumpWriter__

/*********************************************************************
	End of cip error interface header
*********************************************************************/
/* Actifsource ID=[61c1f3bd-5b0a-11e6-b675-316232b1e448,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,eTwz8Bq9GLVDVv9i7buUg8rEx8I=] */
