/*********************************************************************
	SYSTEM CIPLIBRARY
	cip error interface header file 
	Filename: INTF_ProcessDumpHandler.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__INTF_ProcessDumpHandler__)
	#define __INTF_ProcessDumpHandler__

#include <iostream>

namespace ciplibrary
{
	
	/** 
	* Process dump element
	*/
	struct DUMP_Element
	{
		unsigned int processId;
		unsigned int multiplicityIndex;
		int state;
		int mode;
		int modeState;
	};

	/** 
	 * class INTF_ProcessDumpHandler
	 * interface to process dump 
	 */
	class INTF_ProcessDumpHandler
	{
	  public:
	  	INTF_ProcessDumpHandler(void){}
		virtual ~INTF_ProcessDumpHandler(void){}
	    
		/** process dump function */
		virtual void handleProcessDump(struct DUMP_Element *element) = 0;
	    
		/** 
		* Append process dump to the dump element
		*/
		static void appendProcessDump(struct DUMP_Element *element, unsigned int processId, unsigned int multiplicityIndex, int mode, int state, int modeState)
		{
			element->processId = processId;
			element->multiplicityIndex = multiplicityIndex;
			element->mode = mode;
			element->state = state;
			element->modeState = modeState;
		}
	    	
	    	/** 
		* Append process dump to the dump element
		*/
		static void appendProcessDump(struct DUMP_Element *element, unsigned int processId, int state, int modeState)
		{
			appendProcessDump(element, processId, 1, 1, state, modeState);
		}
		
	  private:
	};

} // namespace ciplibrary

#endif // __INTF_ProcessDumpHandler__

/*********************************************************************
	End of cip error interface header
*********************************************************************/
/* Actifsource ID=[2bec3227-319f-11e7-a447-9b7f17a8ec30,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,Hash] */
