/*******************************************************************
        SYSTEM U4_LiftWithAlarmMode_Loesung
        Module for PROCESS Alarmswitch
        Filename: Alarmswitch.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LiftWithAlarmMode 
        	enable mode inspection
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mLiftWithAlarmMode.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Alarmswitch.write_access_
#define STATUS (pStatus_Alarmswitch->read_access_)
#define TIME time_LiftWithAlarmMode
#define fUPDM1_LiftCar() status_LiftCar.write_access_.MODE = \
 	MODTAB_LiftCar[status_Alarmswitch.read_access_.STATE - 1]

/* Process Enumerations */

enum eMODES_Alarmswitch
	{normal = 1};

enum eSTATES_Alarmswitch
	{alarm_off = 1, alarm_on};


/* External Declarations */

extern unsigned long time_LiftWithAlarmMode;
extern struct tCHNOUT_mLiftWithAlarmMode CHNOUT_mLiftWithAlarmMode;
extern union tSTATUS_LiftCar status_LiftCar;
extern const int MODTAB_LiftCar[2];
int fPULSE_LiftCar (enum eOUTPLS_LiftWithAlarmMode name_);

/* Global Declarations */

union tSTATUS_Alarmswitch status_Alarmswitch;
const union tSTATUS_Alarmswitch *pStatus_Alarmswitch = &status_Alarmswitch;

/* Function Prototypes */

void fIMSG_C2_On(void);
void fIMSG_C2_Off(void);
void fINIT_Alarmswitch (void);

/* Input Channel Functions */

void fIMSG_C2_On(void)
{
	switch(status_Alarmswitch.read_access_.STATE)
	{
	case alarm_off:
	 	status_Alarmswitch.write_access_.STATE = alarm_on;
	 	fUPDM1_LiftCar();
	 	fPULSE_LiftCar (O3_blocking);
		break;
	default:
		return;
	}
	return;
}

void fIMSG_C2_Off(void)
{
	switch(status_Alarmswitch.read_access_.STATE)
	{
	case alarm_on:
	 	status_Alarmswitch.write_access_.STATE = alarm_off;
	 	fUPDM1_LiftCar();
	 	fPULSE_LiftCar (O3_release);
		break;
	default:
		return;
	}
	return;
}
		
/* Process Initialization Function */

void fINIT_Alarmswitch (void)
{
	status_Alarmswitch.write_access_.MODE = normal;
	status_Alarmswitch.write_access_.STATE = alarm_off;
}		

/*********************************************************************
	End of Module for PROCESS Alarmswitch
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,474f129b-2ffa-11e2-8ce2-c76b5b13ae26,741c1ae4-2ff8-11e2-8ce2-c76b5b13ae26,278e1b7e-2ffa-11e2-8ce2-c76b5b13ae26,47515c8f-2ffa-11e2-8ce2-c76b5b13ae26,741e64d7-2ff8-11e2-8ce2-c76b5b13ae26,7420d5db-2ff8-11e2-8ce2-c76b5b13ae26,A7jcVSIkmE0euDd2R/4CuXerXGo=] */
