/*******************************************************************
        SYSTEM U4_LiftWithAlarmMode_Loesung
        Module for PROCESS Button
        Filename: Button.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LiftWithAlarmMode 
        	enable mode inspection
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mLiftWithAlarmMode.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Button.write_access_
#define STATUS (pStatus_Button->read_access_)
#define TIME time_LiftWithAlarmMode

/* Process Enumerations */

enum eMODES_Button
	{normal = 1};

enum eSTATES_Button
	{always = 1};


/* External Declarations */

extern unsigned long time_LiftWithAlarmMode;
extern struct tCHNOUT_mLiftWithAlarmMode CHNOUT_mLiftWithAlarmMode;
int fPULSE_LiftCar (enum eOUTPLS_LiftWithAlarmMode name_);

/* Global Declarations */

union tSTATUS_Button status_Button;
const union tSTATUS_Button *pStatus_Button = &status_Button;

/* Function Prototypes */

void fIMSG_C1_push(void);
void fINIT_Button (void);

/* Input Channel Functions */

void fIMSG_C1_push(void)
{
	switch(status_Button.read_access_.STATE)
	{
	case always:
	 	status_Button.write_access_.STATE = always;
	 	fPULSE_LiftCar (O4_push);
		break;
	default:
		return;
	}
	return;
}
		
/* Process Initialization Function */

void fINIT_Button (void)
{
	status_Button.write_access_.MODE = normal;
	status_Button.write_access_.STATE = always;
}		

/*********************************************************************
	End of Module for PROCESS Button
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,474f129b-2ffa-11e2-8ce2-c76b5b13ae26,741c1ae4-2ff8-11e2-8ce2-c76b5b13ae26,278e1b7e-2ffa-11e2-8ce2-c76b5b13ae26,47515c8f-2ffa-11e2-8ce2-c76b5b13ae26,741e64d7-2ff8-11e2-8ce2-c76b5b13ae26,74280206-2ff8-11e2-8ce2-c76b5b13ae26,X2Y7gbkVR1iUTL/vHmiY52khi+U=] */
