/*********************************************************************
	SYSTEM U4_LiftWithAlarmMode_Loesung
	IMPLEMENTATION implementation
	Error Header File for CIP MACHINE mLiftWithAlarmMode
	Filename: eLiftWithAlarmMode.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftWithAlarmMode 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_eLiftWithAlarmMode_hLiftWithAlarmMode_)
	#define _eLiftWithAlarmMode_hLiftWithAlarmMode_

/* Include Files */

#include "mLiftWithAlarmMode.h"

#endif // _eLiftWithAlarmMode_hLiftWithAlarmMode_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLiftWithAlarmMode
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,474f129b-2ffa-11e2-8ce2-c76b5b13ae26,741c1ae4-2ff8-11e2-8ce2-c76b5b13ae26,278e1b7e-2ffa-11e2-8ce2-c76b5b13ae26,47515c8f-2ffa-11e2-8ce2-c76b5b13ae26,rK3zJPWNBTgDLgx/vym9LbGINZg=] */
