/*********************************************************************
  SYSTEM U4_LiftWithAlarmMode_Loesung
  IMPLEMENTATION implementation
  Error Header File for CIP MACHINE mLiftWithAlarmMode
  Filename: mainU4_LiftWithAlarmMode_Loesung_TestSuite_Console.h
  generated by CIP Tool(R)
  
  activated code options:
  	C code
  	use message interface
  		naming option: use default prefix
  	use postfix
  		LiftWithAlarmMode 
  	enable mode inspection
  	'unsigned long' for delays
*********************************************************************/


#ifndef _MAIN_H
#define _MAIN_H

/* === INCLUDE FILES =============================================================== */
#include "sLiftWithAlarmMode.h"

/* === TYPEs =============================================================== */
/** Enum to specify the animation mode. */
typedef enum EAnimationMode
{
  eAnimationMode_Undefined,
  eAnimationMode_Manual,
  eAnimationMode_Regressive,
  eAnimationMode_Runner
} T_EAnimationMode;

/**
 * Returns the current animation mode.
 */
T_EAnimationMode Main_getAnimationMode(void);

#endif // _MAIN_H

/* Actifsource ID=[146c2b3d-30d5-11e7-a447-9b7f17a8ec30,2a93b97e-2ffa-11e2-8ce2-c76b5b13ae26,ipJqbHiGToLYRrXEMueIGR1spVc=] */
