/*********************************************************************
	SYSTEM U4_LiftWithAlarmMode_Loesung
	IMPLEMENTATION implementation
	Module for CIP SHELL sLiftWithAlarmMode
	Filename: sLiftWithAlarmMode.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftWithAlarmMode 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "sLiftWithAlarmMode.h"

/* Input Interface */

struct tIN_LiftWithAlarmMode IN_LiftWithAlarmMode;

/* Output Interface */

struct tOUT_LiftWithAlarmMode OUT_LiftWithAlarmMode;

/* Trigger Interface */

struct tTRG_LiftWithAlarmMode TRG_LiftWithAlarmMode;

/*********************************************************************
	End of Module for CIP SHELL sLiftWithAlarmMode
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,474f129b-2ffa-11e2-8ce2-c76b5b13ae26,741c1ae4-2ff8-11e2-8ce2-c76b5b13ae26,278e1b7e-2ffa-11e2-8ce2-c76b5b13ae26,47515c8f-2ffa-11e2-8ce2-c76b5b13ae26,47515c94-2ffa-11e2-8ce2-c76b5b13ae26,mJDCqfwKc24aLCKrxMu4gZhfHeM=] */
