/*********************************************************************
	SYSTEM U4_LiftWithAlarmMode_Loesung
	IMPLEMENTATION implementation
	Header File for CIP SHELL sLiftWithAlarmMode
	Filename: sLiftWithAlarmMode.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftWithAlarmMode 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_sLiftWithAlarmMode_hLiftWithAlarmMode_)
	#define _sLiftWithAlarmMode_hLiftWithAlarmMode_
/* Code Option Constants */

#if defined(_EINPUT__)
	#undef _EINPUT__
#endif 

#if defined(_PENDING__)
	#undef _PENDING__
#endif 

/* Channel Enumerations */

#if !defined(_eCHAN_LiftWithAlarmMode_)
	#define _eCHAN_LiftWithAlarmMode_

	enum eCHAN_LiftWithAlarmMode
		{C_Act_Motor = 3, C_Evt_Alarm = 2, C_Evt_Button = 1, C_Evt_Lift = 4};

#endif // _eCHAN_LiftWithAlarmMode_

/*********************************************************************
	CODE  GENERATION  FEATURE
	This global message enumeration can be used 
	for implementation purposes.
*********************************************************************/

enum eMSG_LiftWithAlarmModeLiftWithAlarmMode
	{F_C1_push_ = 1, F_C2_On_ = 2, F_C2_Off_ = 3, F_C4_LeaveGrnd_ = 4, 
	 F_C4_LeaveTop_ = 5, F_C4_ReachGrnd_ = 6, F_C4_ReachTop_ = 7, F_C3_MotOff_ = 8, 
	 F_C3_MotScend_ = 9, F_C3_MotRaise_ = 10};

/********************************************************************/

#if !defined(_eMSG_Evt_Button_)
	#define _eMSG_Evt_Button_

	enum eMSG_Evt_Button
		{C1_push = 1};

#endif // _eMSG_Evt_Button_

#if !defined(_eMSG_Evt_Alarm_)
	#define _eMSG_Evt_Alarm_

	enum eMSG_Evt_Alarm
		{C2_On = 1, C2_Off = 2};

#endif // _eMSG_Evt_Alarm_

#if !defined(_eMSG_Act_Motor_)
	#define _eMSG_Act_Motor_

	enum eMSG_Act_Motor
		{C3_MotOff = 1, C3_MotScend = 2, C3_MotRaise = 3};

#endif // _eMSG_Act_Motor_

#if !defined(_eMSG_Evt_Lift_)
	#define _eMSG_Evt_Lift_

	enum eMSG_Evt_Lift
		{C4_LeaveGrnd = 1, C4_LeaveTop = 2, C4_ReachGrnd = 3, C4_ReachTop = 4};

#endif // _eMSG_Evt_Lift_

/* Input Interface Type */

struct tIN_LiftWithAlarmMode
{
	void (*C2_On)(void);
	void (*C2_Off)(void);
	void (*C1_push)(void);
	void (*C4_LeaveGrnd)(void);
	void (*C4_LeaveTop)(void);
	void (*C4_ReachGrnd)(void);
	void (*C4_ReachTop)(void);
};

/* Output Interface Type */

struct tOUT_LiftWithAlarmMode
{
	void (*C3_MotOff)(void);
	void (*C3_MotScend)(void);
	void (*C3_MotRaise)(void);
};


/* Trigger Interface Type */

struct tTRG_LiftWithAlarmMode
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/*  trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
};

/* External Interface Declarations */

extern struct tIN_LiftWithAlarmMode IN_LiftWithAlarmMode;		/* Input Channel Interface defined in sLiftWithAlarmMode.c */
extern struct tOUT_LiftWithAlarmMode OUT_LiftWithAlarmMode;		/* Output Channel Interface defined in sLiftWithAlarmMode.c */
extern struct tTRG_LiftWithAlarmMode TRG_LiftWithAlarmMode;		/* Trigger Interface defined in sLiftWithAlarmMode.c */

/* Unit Initialization Function, defined in mLiftWithAlarmMode.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_LiftWithAlarmMode(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iMSG_LiftWithAlarmMode(void);

#endif // _sLiftWithAlarmMode_hLiftWithAlarmMode_

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sLiftWithAlarmMode
*********************************************************************/
/* Actifsource ID=[b7934a9b-259a-11e1-ae2f-a14f3e396de6,474f129b-2ffa-11e2-8ce2-c76b5b13ae26,741c1ae4-2ff8-11e2-8ce2-c76b5b13ae26,278e1b7e-2ffa-11e2-8ce2-c76b5b13ae26,47515c8f-2ffa-11e2-8ce2-c76b5b13ae26,47515c94-2ffa-11e2-8ce2-c76b5b13ae26,Grq6GPikOn0A77z0e4jqedc4He8=] */
