/*********************************************************************
	SYSTEM U4_LiftWithAlarmMode_Loesung
	IMPLEMENTATION implementation
	Trace Interface Module for CIP MACHINE mLiftWithAlarmMode
	Filename: tLiftWithAlarmMode.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LiftWithAlarmMode 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "tLiftWithAlarmMode.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLiftWithAlarmMode
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,474f129b-2ffa-11e2-8ce2-c76b5b13ae26,741c1ae4-2ff8-11e2-8ce2-c76b5b13ae26,278e1b7e-2ffa-11e2-8ce2-c76b5b13ae26,47515c8f-2ffa-11e2-8ce2-c76b5b13ae26,vah6aGYVitISueFday31Fwnq4q8=] */
