/*********************************************************************
	SYSTEM CIPLIBRARY
	cip chain queue header file 
	Filename: CipChainQueue.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__CipChainQueue__)
	#define __CipChainQueue__

#include "CipList.hpp"
#include "CipChain.hpp"

namespace ciplibrary
{
	
	/** 
	 * class CipChainQueue
	 * linked list for chain elements as fifo queue
	 */
	
	template<class P >
	class CipChainQueue
	{
	public: 
		
		/** consructors / destructors */
		CipChainQueue(void);
		virtual ~CipChainQueue(void){}
		
		/** insert the chain element at the end of the queue. */
		void setChain(CipChain<P >* i_chain);
		
		/** trigger the process with CHAIN_ */
		void CHAIN_(void);
		
		/** return whether any chain element is in the queue */
		bool hasCHAIN_(void) const;

	private: 
		
		/** prohibitted default functions */
		CipChainQueue(const CipChainQueue&);
		CipChainQueue& operator=(const CipChainQueue&);

		
		/** member variables */
		CipList<CipChain<P > > m_list;

	}; // class CipChainQueue

/*********************************************************************
*********************************************************************/

	
	/** consructors / destructors */
	template<class P >
	CipChainQueue<P >::CipChainQueue(void) : 
		m_list(&CipChain<P >::getNext)
	{} // constructor()
	
	/** insert the chain element at the end of the queue. */
	template<class P >
	void CipChainQueue<P >::setChain(CipChain<P >* i_chain)
	{
		if (!m_list.empty())
		{
			m_list.remove(i_chain);
		}
		m_list.push_back(i_chain);
	} // setChain()
	
	/** trigger the process with CHAIN_ */
	template<class P >
	void CipChainQueue<P >::CHAIN_(void)
	{
		if (m_list.empty())
		{
			return;
		}
		m_list.pop_front()->CHAIN_();
	} // CHAIN_()
	
	/** return whether any chain element is in the queue */
	template<class P >
	bool CipChainQueue<P >::hasCHAIN_(void) const
	{
		return !m_list.empty();
	} // hasCHAIN_()

} // namespace ciplibrary

#endif // __CipChainQueue__

/*********************************************************************
	End of cip chain queue header
*********************************************************************/
/* Actifsource ID=[fc2aa69b-08ab-11e3-b902-17aaca85d2fd,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,5OMA/V3hkYdsBVP7IOGdkWBCZaU=] */
