/*********************************************************************
	SYSTEM CIPLIBRARY
	cip common names header file 
	Filename: INTF_CommonNames.hpp
	generated by CIP Tool(R)
	activated code options:
		C++ code
*********************************************************************/

#if !defined(__INTF_CommonNames__)
	#define __INTF_CommonNames__

#include <string.h>

namespace ciplibrary
{
	
	/** 
	 * class INTF_CommonNames
	 * common cip names
	 */
	class INTF_CommonNames
	{
	public: 

		enum E_CommonNames
		{
			_no_input_ = 0, 
			AUTO_ = 1, 
			CHAIN_ = 2, 
			TIMEUP_ = 3, 
			_no_outpulse_ = 4, 
			READ_ = 5, 
			STEP_ = 6, 
			INFO_ = 7, 
			TIME = 8, 
			_no_TC_ = 9, 
			TM_SET = 10, 
			TM_UP = 11, 
			CH_SET = 12
		};

	private: 
	}; // class INTF_CommonNames

} // namespace ciplibrary

#endif // __INTF_CommonNames__

/*********************************************************************
	End of cip common names header
*********************************************************************/
/* Actifsource ID=[4ff70535-08ad-11e3-b902-17aaca85d2fd,a6d1b8c9-cedd-11de-80c2-87ac3b08f930,1aBFBpJJCleQkY/FjjspjYNKyk0=] */
