/*********************************************************************
	SYSTEM HistorystateSystem
	IMPLEMENTATION Historystate_cpp
	cip machine factory file for CIP SHELL sHistorystateSUnit
	Filename: FCTY_mHistorystateSUnit.cpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        'unsigned long' for delays
*********************************************************************/

#include "FCTY_mHistorystateSUnit.hpp"
#include "CIPM_mHistorystateSUnit.hpp"

namespace historystatesunit
{
	namespace cipshell
	{
        
		/** Creates a new CIP Machine
		* parameter: pointer to the Action Message Handler created by user
		* return: pointer to the CIP Machine */
		INTF_mHistorystateSUnit* FCTY_mHistorystateSUnit::cipmachine(INTF_ActionMessagePort* i_amp)
		{
			historystatesunit::cipmachine::CIPM_mHistorystateSUnit* m_cipmachine = 
				new historystatesunit::cipmachine::CIPM_mHistorystateSUnit(i_amp);
			return m_cipmachine;
		} // cipmachine()

	} // namespace cipshell
} // namespace historystatesunit

/*********************************************************************
    End of cip machine factory for CIP SHELL sHistorystateSUnit
*********************************************************************/
/* Actifsource ID=[c16b5c94-08dd-11e3-b902-17aaca85d2fd,1d05cec7-9ac1-11ef-9dfa-835f60e5a95d,73ed890e-9ac0-11ef-9dfa-835f60e5a95d,f0198f93-9ac0-11ef-9dfa-835f60e5a95d,1d05cec6-9ac1-11ef-9dfa-835f60e5a95d,1d05cec5-9ac1-11ef-9dfa-835f60e5a95d,Zxx5NeTS5Dqxu12ftAKvIGztvMw=] */
