/*********************************************************************
	SYSTEM HistorystateSystem
	IMPLEMENTATION Historystate_cpp
	constants interface file for CIP SHELL sHistorystateSUnit
	Filename: INTF_Constant.cpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        'unsigned long' for delays
*********************************************************************/

#include "INTF_Constant.hpp"

namespace historystatesunit
{
	namespace cipshell
	{
	} // namespace cipshell
} // namespace historystatesunit

/*********************************************************************
    End of constants interface for CIP SHELL sHistorystateSUnit
*********************************************************************/
/* Actifsource ID=[baaf3bef-0965-11e3-b902-17aaca85d2fd,1d05cec7-9ac1-11ef-9dfa-835f60e5a95d,73ed890e-9ac0-11ef-9dfa-835f60e5a95d,f0198f93-9ac0-11ef-9dfa-835f60e5a95d,1d05cec6-9ac1-11ef-9dfa-835f60e5a95d,1d05cec5-9ac1-11ef-9dfa-835f60e5a95d,6u0Zots++MQR1bPcFQlYytKDP2k=] */
