/*********************************************************************
	SYSTEM HistorystateSystem
	IMPLEMENTATION Historystate_cpp
	cip machine interface header file for CIP SHELL sHistorystateSUnit
	Filename: INTF_mHistorystateSUnit.hpp
	generated by CIP Tool(R)
	
	activated code options:
		C++ code
		use message interface
	            naming option: channel  prefix
	        all types in shell
	        'unsigned long' for delays
*********************************************************************/

#if !defined(__INTF_mHistorystateSUnit__)
    #define __INTF_mHistorystateSUnit__

#include "INTF_CipMachine.hpp"

namespace historystatesunit
{
	namespace cipshell
	{
        
		/** 
		* class INTF_mHistorystateSUnit
		* interface declaring input messages for cip machine
		*/
		class INTF_mHistorystateSUnit : 
			public ciplibrary::INTF_CipMachine
		{
		public: 
            
			/** constructors / destructors */
			INTF_mHistorystateSUnit(void){}
			virtual ~INTF_mHistorystateSUnit(void){}

			/** event message interface */
			/**
			* Triggers CIP Machine by input message doMachineStuff (channel Event_1).
			*/
			virtual void C1_doMachineStuff(void) = 0;
            
			/**
			* Triggers CIP Machine by input message nextWorkload (channel Event_1).
			*/
			virtual void C1_nextWorkload(void) = 0;
            
			/**
			* Triggers CIP Machine by input message powerFail (channel Event_1).
			*/
			virtual void C1_powerFail(void) = 0;
            
			/**
			* Triggers CIP Machine by input message powerOff (channel Event_1).
			*/
			virtual void C1_powerOff(void) = 0;
            
			/**
			* Triggers CIP Machine by input message powerOn (channel Event_1).
			*/
			virtual void C1_powerOn(void) = 0;
            
			/**
			* Triggers CIP Machine by input message doMachineStuff (channel Event_2).
			*/
			virtual void C2_doMachineStuff(void) = 0;
            
			/**
			* Triggers CIP Machine by input message nextWorkload (channel Event_2).
			*/
			virtual void C2_nextWorkload(void) = 0;
            
			/**
			* Triggers CIP Machine by input message powerFail (channel Event_2).
			*/
			virtual void C2_powerFail(void) = 0;
            
			/**
			* Triggers CIP Machine by input message powerOff (channel Event_2).
			*/
			virtual void C2_powerOff(void) = 0;
            
			/**
			* Triggers CIP Machine by input message powerOn (channel Event_2).
			*/
			virtual void C2_powerOn(void) = 0;
            
			/** 
			* global unit time
			*/
			unsigned long TIME;

		private: 
            
			/** prohibitted default functions */
			INTF_mHistorystateSUnit(const INTF_mHistorystateSUnit&);
			INTF_mHistorystateSUnit& operator=(const INTF_mHistorystateSUnit&);

		}; // class INTF_mHistorystateSUnit

	} // namespace cipshell
} // namespace historystatesunit

#endif // __INTF_mHistorystateSUnit__

/*********************************************************************
    End of cip machine interface header for CIP SHELL sHistorystateSUnit
*********************************************************************/
/* Actifsource ID=[6628a6cc-08f0-11e3-b902-17aaca85d2fd,1d05cec7-9ac1-11ef-9dfa-835f60e5a95d,73ed890e-9ac0-11ef-9dfa-835f60e5a95d,f0198f93-9ac0-11ef-9dfa-835f60e5a95d,1d05cec6-9ac1-11ef-9dfa-835f60e5a95d,1d05cec5-9ac1-11ef-9dfa-835f60e5a95d,El94/3ce7/xbwOc9MMQAyeBRFt4=] */
