/*********************************************************************
	SYSTEM Kesselsteuerung_Loesung
	IMPLEMENTATION implementation
	Error Header File for CIP MACHINE mKesselUnit
	Filename: eKesselUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_eKesselUnit_hKesselUnit_)
	#define _eKesselUnit_hKesselUnit_

/* Include Files */

#include "mKesselUnit.h"

#endif // _eKesselUnit_hKesselUnit_

/*********************************************************************
	End of Error Header File for CIP MACHINE mKesselUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,304ffac5-2fda-11e2-a23a-331776341c66,5b61a23d-2fd9-11e2-a23a-331776341c66,21741d8a-2fda-11e2-a23a-331776341c66,305244b9-2fda-11e2-a23a-331776341c66,Hir7W9OGoKtlw1UjVKR3q/zI2/Q=] */
