/*********************************************************************
	SYSTEM Kesselsteuerung_Loesung
	IMPLEMENTATION implementation
	Error Interface Module for CIP MACHINE mKesselUnit
	Filename: eKesselUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "eKesselUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mKesselUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,304ffac5-2fda-11e2-a23a-331776341c66,5b61a23d-2fd9-11e2-a23a-331776341c66,21741d8a-2fda-11e2-a23a-331776341c66,305244b9-2fda-11e2-a23a-331776341c66,mZVzGNbBY83k8nsE23Nt5imnVpM=] */
