/*********************************************************************
  SYSTEM Kesselsteuerung_Loesung
  IMPLEMENTATION implementation
  Error Header File for CIP MACHINE mKesselUnit
  Filename: mainKesselsteuerung_Loesung_TestSuite_Console.c
  generated by CIP Tool(R)
  
  activated code options:
  	C code
  	use message interface
  		naming option: use default prefix
  	use postfix
  		KesselUnit 
  	enable mode inspection
  	'unsigned long' for delays
*********************************************************************/

/* Begin Protected Region [[include]] */

/* End Protected Region   [[include]] */
#include "mainKesselsteuerung_Loesung_TestSuite_Console.h"
#include "tKesselUnit.h"
#include "animation/MessageHandler.h"
#include "animation/DataHandler.h"

#include <stdio.h>
#include <string.h>

#define VAR (*var_)

/** Enum to specify the trace mode. */
typedef enum ETraceMode
{
  eTrace_Disable,
  eTrace_Enable
} T_ETraceMode;

/** Enum variable to specify the animation mode. */
T_EAnimationMode g_eAnimationMode = eAnimationMode_Undefined;

/** Enum variable to specify the trace mode. */
T_ETraceMode g_eTraceMode = eTrace_Disable;

/** Enum for all event messages of this system. */
typedef enum EEventMessage
{
  eEventMessage_Quit = -1,
  eEventMessage_Tick = 0,
  eEventMessage_Step,
  eEventMessage_TimeUp,
  eEventMessage_Chain,
  eEventMessage_Read,
  eEventMessage_Auto,
  eEventMessage_Evt_HauptSchalter_KesselAus,
  eEventMessage_Evt_HauptSchalter_KesselEin,
  eEventMessage_Evt_Kessel_UeberN1,
  eEventMessage_Evt_Kessel_UeberN2,
  eEventMessage_Evt_Kessel_UnterN1,
  eEventMessage_Evt_Kessel_UnterN2,
  eEventMessage_Evt_TempRegler_UeberT,
  eEventMessage_Evt_TempRegler_UnterT,
  eEventMessageCount
} T_EEventMessage; 

/** Enum for all action messages of this system. */
typedef enum EActionMessage
{
  eActionContextError = 0,
  eActionFullBufferWarning,
  eActionBufferError,
  eActionPulseSelectionError,
  eActionMessageSelectionError,
  eActionInputError,
  eActionMessage_Act_Kessel_Fuellen,
  eActionMessage_Act_Kessel_Leeren,
  eActionMessage_Act_TempRegler_HeizAus,
  eActionMessage_Act_TempRegler_HeizEin,
  eActionMessageCount
} T_EActionMessage; 

/** Enum for all test case. */
typedef enum ETestCase
{
  eTestCase_KesselTest
} T_ETestCase;

/* Checked output message */
const int checkedOutputMessage_KesselTest[eActionMessageCount] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

/** Typedef of all Event data. */
typedef union UEventData
{
  int tick;
} T_UEventData;




/** Recorded action message of this system. */
typedef struct SRecordedActionMessage
{
  T_EActionMessage actionMessage;
} T_RecordedActionMessage;

/** Maximum action messages which can be recorded per event message for automatic animation. */
enum {g_nMaxRecordedActionMessageCount = 100};

/** The number of recorded action messages. */
int g_nRecordedActionMessageCount = 0;

/** The number of expected action messages. */
int g_nExpectedActionMessageCount = 0;

/** An array which contains the recorded action messages. */
T_RecordedActionMessage g_eRecordedActionMessage[g_nMaxRecordedActionMessageCount];

/** System Tick. */
int s_nSystemTick = 0;

t_ConnectionContext s_connectionContext;

/* Active Test Case */
T_ETestCase activeTestCase;

/**
 * Returns the current animation connection
 */
t_ConnectionContext* Main_getConnectionContext(void) 
{
  return &s_connectionContext;
}

/**
 * Returns the current animation mode.
 */
T_EAnimationMode Main_getAnimationMode(void)
{
  return g_eAnimationMode;
}

/**
 * Checked output message
 */
char isCheckedOutputMessage(T_EActionMessage i_eActionMessage)
{
  switch (activeTestCase)
  {
     case eTestCase_KesselTest:
       return checkedOutputMessage_KesselTest[i_eActionMessage];
     default:
       return 0;
     break;
  }
  return 1;
}

/**
 *  Translates the given action message enum to string.
 *  @param i_eActionMessage The message type to translate.
 *  @return The translated action message or 0 if enum not found.
 */
const char* const translateActionMessage(T_EActionMessage i_eActionMessage)
{
  switch (i_eActionMessage)
  {
    case eActionMessage_Act_Kessel_Fuellen:
      return "Act_Kessel.Fuellen";
    break;
    case eActionMessage_Act_Kessel_Leeren:
      return "Act_Kessel.Leeren";
    break;
    case eActionMessage_Act_TempRegler_HeizAus:
      return "Act_TempRegler.HeizAus";
    break;
    case eActionMessage_Act_TempRegler_HeizEin:
      return "Act_TempRegler.HeizEin";
    break;
    case eActionMessageCount:
      return 0;
    break;
    default:
      return 0;
    break;
  }
  return 0;
}

/**
 *  Check if the Action message has equals data.
 *  @param i_eActionMessage The message type to translate.
 *  @return The action message is equals 1 or 0 if not.
 */
char equalsActionMessageData(T_RecordedActionMessage sActionMessage, T_RecordedActionMessage sRecordedActionMessage)
{
  switch (sRecordedActionMessage.actionMessage)
  {
    case eActionMessage_Act_Kessel_Fuellen:
      return 1;
    break;
    case eActionMessage_Act_Kessel_Leeren:
      return 1;
    break;
    case eActionMessage_Act_TempRegler_HeizAus:
      return 1;
    break;
    case eActionMessage_Act_TempRegler_HeizEin:
      return 1;
    break;
    case eActionMessageCount:
      return 1;
    break;
    default:
      return 1;
    break;
  }
  return 1;
}

/**
 *  Check if the Action message has equals index.
 *  @param i_eActionMessage The message type to translate.
 *  @return The action message is equals 1 or 0 if not.
 */
char equalsActionMessageIndex(T_RecordedActionMessage sActionMessage, T_RecordedActionMessage sRecordedActionMessage)
{
  switch (sRecordedActionMessage.actionMessage)
  {
    case eActionMessage_Act_Kessel_Fuellen:
      return 1;
    break;
    case eActionMessage_Act_Kessel_Leeren:
      return 1;
    break;
    case eActionMessage_Act_TempRegler_HeizAus:
      return 1;
    break;
    case eActionMessage_Act_TempRegler_HeizEin:
      return 1;
    break;
    case eActionMessageCount:
      return 1;
    break;
    default:
      return 1;
    break;
  }
  return 1;
}

/**
 *  Records the message action from the cip system.
 *  @param i_eActionMessage The message type to record.
 */
void recordMessageAction(T_RecordedActionMessage sRecordedActionMessage)
{
  if (g_nRecordedActionMessageCount>=g_nMaxRecordedActionMessageCount) {return;}
  g_eRecordedActionMessage[g_nRecordedActionMessageCount++] = sRecordedActionMessage;
}

/**
 *  Asserts the message action from the cip system.
 *  @param i_eActionMessage The action message type to compare.
 *  @param i_pcTestEventGuid The guid of the test event.
 *  @param i_pcActionMessageGuid The guid of the action message to compare.
 *  @return 1 if recoreded and expected message actions are equal. 0 if not.
 *  @warning Previously record message actions with recordMessageAction()
 */
int assertMessageAction(T_RecordedActionMessage sRecordedActionMessage, const char* const i_pcTestEventGuid, const char* const i_pcActionMessageGuid, const char* const i_testCaseName, int checkData)
{
  if (g_nExpectedActionMessageCount >= g_nRecordedActionMessageCount) 
  {
    if (g_eAnimationMode == eAnimationMode_Runner) {
       printf("4ae31ce4-2fda-11e2-a23a-331776341c66.asr: Failure\n");
       printf("TestCase: %s\n", i_testCaseName);
    }
    printf("    ASSERTION FAILED: %s\n",i_pcTestEventGuid);
    printf("    > Expected: ActionMessage #%i = %s %s\n", g_nExpectedActionMessageCount, translateActionMessage(sRecordedActionMessage.actionMessage), i_pcActionMessageGuid);
    printf("    > Recorded: -\n");
    return 0;
  }
  T_RecordedActionMessage sActionMessage = g_eRecordedActionMessage[g_nExpectedActionMessageCount++];
  if (sActionMessage.actionMessage != sRecordedActionMessage.actionMessage)
  {
    if (g_eAnimationMode == eAnimationMode_Runner) {
       printf("4ae31ce4-2fda-11e2-a23a-331776341c66.asr: Failure\n");
       printf("TestCase: %s\n", i_testCaseName);
    }
    printf("    ASSERTION FAILED: %s\n",i_pcTestEventGuid);
    printf("    > Expected: ActionMessage #%i = %s %s\n", g_nExpectedActionMessageCount, translateActionMessage(sRecordedActionMessage.actionMessage), i_pcActionMessageGuid);
    printf("    > Recorded: ActionMessage #%i = %s\n", g_nExpectedActionMessageCount, translateActionMessage(sActionMessage.actionMessage));
    return 0;
  }
  if (!equalsActionMessageIndex(sActionMessage, sRecordedActionMessage)) 
  {
    if (g_eAnimationMode == eAnimationMode_Runner) {
       printf("4ae31ce4-2fda-11e2-a23a-331776341c66.asr: Failure\n");
       printf("TestCase: %s\n", i_testCaseName);
    }
    printf("    ASSERTION FAILED: %s\n",i_pcTestEventGuid);
    printf("    > Expected: ActionMessage index not equals #%i = %s %s\n", g_nExpectedActionMessageCount, translateActionMessage(sRecordedActionMessage.actionMessage), i_pcActionMessageGuid);
    printf("    > Recorded: ActionMessage index not equals #%i = %s\n", g_nExpectedActionMessageCount, translateActionMessage(sActionMessage.actionMessage));
    return 0;
  }
  if (!checkData) return 1;
  if (!equalsActionMessageData(sActionMessage, sRecordedActionMessage)) 
  {
    if (g_eAnimationMode == eAnimationMode_Runner) {
       printf("4ae31ce4-2fda-11e2-a23a-331776341c66.asr: Failure\n");
       printf("TestCase: %s\n", i_testCaseName);
    }
    printf("    ASSERTION FAILED: %s\n",i_pcTestEventGuid);
    printf("    > Expected: ActionMessage data not equals #%i = %s %s\n", g_nExpectedActionMessageCount, translateActionMessage(sRecordedActionMessage.actionMessage), i_pcActionMessageGuid);
    printf("    > Recorded: ActionMessage data not equals #%i = %s\n", g_nExpectedActionMessageCount, translateActionMessage(sActionMessage.actionMessage));
    return 0;
  }
  return 1;
}

/**
 *  Asserts and resets the message action count variable.
 *  @param i_pcTestEventGuid The guid of the test event.
 *  @return 1 if recoreded and expected message action counts are equal. 0 if not.
 */
int assertMessageActionCount(const char* const i_pcTestEventGuid, const char* const i_testCaseName)
{
  int bEqualMessageActionCount = g_nExpectedActionMessageCount == g_nRecordedActionMessageCount;
  if (!bEqualMessageActionCount)
  {
    if (g_eAnimationMode == eAnimationMode_Runner) {
       printf("4ae31ce4-2fda-11e2-a23a-331776341c66.asr: Failure\n");
       printf("TestCase: %s\n", i_testCaseName);
    }
    printf("    ASSERTION FAILED: %s\n",i_pcTestEventGuid);
    printf("    > Expected: -\n");
    for (;g_nExpectedActionMessageCount<g_nRecordedActionMessageCount;++g_nExpectedActionMessageCount)
    {
      printf("    > Recorded: ActionMessage #%i = %s\n", g_nExpectedActionMessageCount+1,translateActionMessage(g_eRecordedActionMessage[g_nExpectedActionMessageCount].actionMessage));
    }
  }
  g_nRecordedActionMessageCount = 0;
  g_nExpectedActionMessageCount = 0;
  return bEqualMessageActionCount;
}

/**
 *  Function forward.
 */
void sendTickEvent(int i_nTickCount, int i_bAutoTimeup);
void sendStepEvent();
void sendChainEvent();
void sendAutoEvent();
void sendTimeupEvent();
void sendReadEvent();

/** 
 *  Sends the message event to the cip system.
 *  @param i_eEventMessage The message type to send.
 *  @param i_bAutoStep Automatically calls STEP_ if 1. Calls STEP_ for all pending events if code option enable_PENDING_Information set.
 *  @return 1 if ok. 0 if failed.
 */
int sendMessageEvent(T_EEventMessage i_eEventMessage, int i_bAutoStep, int i_bAutoTimeup, T_UEventData *eventData )
{
  switch (i_eEventMessage)
  {
    case eEventMessage_Tick:
      sendTickEvent(eventData->tick, i_bAutoTimeup);
    break;
    case eEventMessage_Step:
      sendStepEvent();
    break;
    case eEventMessage_TimeUp:
      sendTimeupEvent();
    break;
    case eEventMessage_Chain:
      sendChainEvent();
    break;
    case eEventMessage_Read:
      sendReadEvent();
    break;
    case eEventMessage_Auto:
      sendAutoEvent();
    break;
    case eEventMessage_Evt_HauptSchalter_KesselAus:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_HauptSchalter.KesselAus  \n");}
      IN_KesselUnit.C2_KesselAus();
    break;
    case eEventMessage_Evt_HauptSchalter_KesselEin:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_HauptSchalter.KesselEin  \n");}
      IN_KesselUnit.C2_KesselEin();
    break;
    case eEventMessage_Evt_Kessel_UeberN1:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_Kessel.UeberN1  \n");}
      IN_KesselUnit.C3_UeberN1();
    break;
    case eEventMessage_Evt_Kessel_UeberN2:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_Kessel.UeberN2  \n");}
      IN_KesselUnit.C3_UeberN2();
    break;
    case eEventMessage_Evt_Kessel_UnterN1:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_Kessel.UnterN1  \n");}
      IN_KesselUnit.C3_UnterN1();
    break;
    case eEventMessage_Evt_Kessel_UnterN2:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_Kessel.UnterN2  \n");}
      IN_KesselUnit.C3_UnterN2();
    break;
    case eEventMessage_Evt_TempRegler_UeberT:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_TempRegler.UeberT  \n");}
      IN_KesselUnit.C5_UeberT();
    break;
    case eEventMessage_Evt_TempRegler_UnterT:
      if (g_eTraceMode == eTrace_Enable) {printf(" EventMessage: Evt_TempRegler.UnterT  \n");}
      IN_KesselUnit.C5_UnterT();
    break;
    default:
      return 0;
    break;
  }
  {
    if (g_eTraceMode == eTrace_Enable) {printf(" STEP_\n");}
    int maxStepCount = 0;
    for (maxStepCount=0;maxStepCount<i_bAutoStep;maxStepCount++) 
    {
      TRG_KesselUnit.STEP_();
    }
  }
  return 1;
}

/** 
 *  Sends the tick event to the cip system.
 *  @param i_nTickCount The number of ticks.
 *  @param i_bAutoTimeup Calls TIMEUP_ after each tick if set.
 */
void sendTickEvent(int i_nTickCount, int i_bAutoTimeup)
{
  int nTickCount;
  int nAutoCount;
  if (g_eTraceMode == eTrace_Enable) {printf(" START TICK_ #%i\n",s_nSystemTick);}  
  if (g_eAnimationMode == eAnimationMode_Visual) {
    char message[100];
    JsonUtl_initStringBuffer(message);
    JsonUtl_appendString(message, "START TICK_ ");
    JsonUtl_appendInteger(message, s_nSystemTick);
    MessageHandler_sendTestbenchLogResponse(&s_connectionContext, message);
  }
  for (nTickCount=0;nTickCount<i_nTickCount;++nTickCount)
  {
    s_nSystemTick++;
    TRG_KesselUnit.TICK_(); 
    for(nAutoCount=0;nAutoCount<i_bAutoTimeup;nAutoCount++)  
    {
      TRG_KesselUnit.TIMEUP_();
    }
  }
  if (g_eAnimationMode == eAnimationMode_Visual) {
    char message[100];
    JsonUtl_initStringBuffer(message);
    JsonUtl_appendString(message, "END TICK_ ");
    JsonUtl_appendInteger(message, s_nSystemTick);
    MessageHandler_sendTestbenchLogResponse(&s_connectionContext, message);
  }
  if (g_eTraceMode == eTrace_Enable) {printf(" END TICK_ #%i\n",s_nSystemTick);}
}

/** 
 *  Sends the step event to the cip system.
 */
void sendStepEvent()
{
  if (g_eTraceMode == eTrace_Enable) {printf(" STEP_\n");}
  TRG_KesselUnit.STEP_();
}

/** 
 *  Sends the chain event to the cip system.
 */
void sendChainEvent()
{
  if (g_eTraceMode == eTrace_Enable) {printf(" CHAIN_\n");}
  TRG_KesselUnit.CHAIN_(); 
}

/** 
 *  Sends the timeup event to the cip system.
 */
void sendTimeupEvent()
{
  if (g_eTraceMode == eTrace_Enable) {printf(" TIMEUP_\n");}
  TRG_KesselUnit.TIMEUP_(); 
}

/** 
 *  Sends the read event to the cip system.
 */
void sendReadEvent()
{
  if (g_eTraceMode == eTrace_Enable) {printf(" READ_\n");}
  TRG_KesselUnit.READ_(); 
}

/** 
 *  Sends the auto event to the cip system.
 */
void sendAutoEvent()
{
  if (g_eTraceMode == eTrace_Enable) {printf(" AUTO_\n");}
  TRG_KesselUnit.AUTO_(); 
}

/** 
 *  Act_Kessel.Fuellen action message callback (Action Initiation).
 */
void AI_KesselUnit_C4_Fuellen()
{
  if (g_eTraceMode == eTrace_Enable) {printf("   ActionMessage: Act_Kessel.Fuellen \n\n");}
  if (g_eAnimationMode == eAnimationMode_Regressive || g_eAnimationMode == eAnimationMode_Runner) {
    T_RecordedActionMessage sRecorded;
    sRecorded.actionMessage = eActionMessage_Act_Kessel_Fuellen;
    if (!isCheckedOutputMessage(sRecorded.actionMessage)) return;
    recordMessageAction(sRecorded);
  }
  if (g_eAnimationMode == eAnimationMode_Visual) {
    MessageHandler_sendTestbenchAction(&s_connectionContext, eActionMessage_Act_Kessel_Fuellen, NULL, NULL);
  }
}

/** 
 *  Act_Kessel.Leeren action message callback (Action Initiation).
 */
void AI_KesselUnit_C4_Leeren()
{
  if (g_eTraceMode == eTrace_Enable) {printf("   ActionMessage: Act_Kessel.Leeren \n\n");}
  if (g_eAnimationMode == eAnimationMode_Regressive || g_eAnimationMode == eAnimationMode_Runner) {
    T_RecordedActionMessage sRecorded;
    sRecorded.actionMessage = eActionMessage_Act_Kessel_Leeren;
    if (!isCheckedOutputMessage(sRecorded.actionMessage)) return;
    recordMessageAction(sRecorded);
  }
  if (g_eAnimationMode == eAnimationMode_Visual) {
    MessageHandler_sendTestbenchAction(&s_connectionContext, eActionMessage_Act_Kessel_Leeren, NULL, NULL);
  }
}

/** 
 *  Act_TempRegler.HeizAus action message callback (Action Initiation).
 */
void AI_KesselUnit_C6_HeizAus()
{
  if (g_eTraceMode == eTrace_Enable) {printf("   ActionMessage: Act_TempRegler.HeizAus \n\n");}
  if (g_eAnimationMode == eAnimationMode_Regressive || g_eAnimationMode == eAnimationMode_Runner) {
    T_RecordedActionMessage sRecorded;
    sRecorded.actionMessage = eActionMessage_Act_TempRegler_HeizAus;
    if (!isCheckedOutputMessage(sRecorded.actionMessage)) return;
    recordMessageAction(sRecorded);
  }
  if (g_eAnimationMode == eAnimationMode_Visual) {
    MessageHandler_sendTestbenchAction(&s_connectionContext, eActionMessage_Act_TempRegler_HeizAus, NULL, NULL);
  }
}

/** 
 *  Act_TempRegler.HeizEin action message callback (Action Initiation).
 */
void AI_KesselUnit_C6_HeizEin()
{
  if (g_eTraceMode == eTrace_Enable) {printf("   ActionMessage: Act_TempRegler.HeizEin \n\n");}
  if (g_eAnimationMode == eAnimationMode_Regressive || g_eAnimationMode == eAnimationMode_Runner) {
    T_RecordedActionMessage sRecorded;
    sRecorded.actionMessage = eActionMessage_Act_TempRegler_HeizEin;
    if (!isCheckedOutputMessage(sRecorded.actionMessage)) return;
    recordMessageAction(sRecorded);
  }
  if (g_eAnimationMode == eAnimationMode_Visual) {
    MessageHandler_sendTestbenchAction(&s_connectionContext, eActionMessage_Act_TempRegler_HeizEin, NULL, NULL);
  }
}


/** 
 *  Shell Initialization Function. 
 */
void iMSG_KesselUnit()
{
  OUT_KesselUnit.C4_Fuellen = AI_KesselUnit_C4_Fuellen;
  OUT_KesselUnit.C4_Leeren = AI_KesselUnit_C4_Leeren;
  OUT_KesselUnit.C6_HeizAus = AI_KesselUnit_C6_HeizAus;
  OUT_KesselUnit.C6_HeizEin = AI_KesselUnit_C6_HeizEin;
  /* Input error */
}

/** 
 *  Pointer to User defined Trace dump Function. 
 */
void TRACE_KesselUnit_DUMP (struct tTRACE_DUMP_KesselUnit *element)
{
  if (g_eAnimationMode == eAnimationMode_Visual)
  {
    t_ConnectionData *connectionData = MessageHandler_getConnectionData(&s_connectionContext);
    if (connectionData->isBinded) 
    {
      connectionData->sequenceNumber = 0;
      MessageHandler_sendElement(&s_connectionContext, element->processId, element->multiplicityIndex, element->modeState, 0);
    }
  }
}

/** 
 *  Pointer to User defined Trace state change Function. 
 */
void TRACE_KesselUnit_CHANGE (unsigned char elementCount, struct tTRACE_CHANGE_KesselUnit elements[])
{
  if (g_eAnimationMode == eAnimationMode_Visual)
  {
    int index = 0;
    t_ConnectionData *connectionData = MessageHandler_getConnectionData(&s_connectionContext);  
    if (connectionData->isBinded) 
    {
      connectionData->sequenceNumber++;
      for(index = 0; index < elementCount; index++) {
        MessageHandler_sendElement(&s_connectionContext, elements[index].processId, elements[index].multiplicityIndex, elements[index].changeId, connectionData->sequenceNumber);
      }
    }
  }
}

/** 
 *  Trace initialization Function. 
 */
void iTRACE_KesselUnit(void)
{
 TRACE_KesselUnit.DUMP_ = TRACE_KesselUnit_DUMP;
 TRACE_KesselUnit.CHANGE_ = TRACE_KesselUnit_CHANGE;
}

/** Forward TestCase KesselTest */
int testCase_KesselTest(int mainTestCase);

/** 
 *  TestCase KesselTest
 *  mainTestCase 1 if main test case, 0 if sub test case.
 *  @return 1 if test case ok. 0 if test case failed.
 */
int testCase_KesselTest(int mainTestCase)
{
  T_UEventData data;
  T_RecordedActionMessage sRecorded;
  
  if (mainTestCase) 
  {
    printf(">>> TestCase KesselTest [b0025141-e1c7-11e3-bb00-f724347870c1]\n");
    s_nSystemTick = 0;
    g_nRecordedActionMessageCount = 0;
    g_nExpectedActionMessageCount = 0;
    if (!fINIT_KesselUnit()) 
    {
      printf("\nInitialization failed\n"); 
      return 0;
    }
  }
  
  activeTestCase = eTestCase_KesselTest;
  sendMessageEvent(eEventMessage_Evt_HauptSchalter_KesselEin, 1, 1, &data);
  sRecorded.actionMessage = eActionMessage_Act_Kessel_Fuellen;
  if (!assertMessageAction(sRecorded,"TestEvent Evt_HauptSchalter.KesselEin [a52696a6-b78e-11ea-848b-a5c54ed864b3]","[a5384a06-b78e-11ea-848b-a5c54ed864b3]", "KesselTest" ,0)) {return 0;}
  if (!assertMessageActionCount("TestEvent Evt_HauptSchalter.KesselEin [a52696a6-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_Kessel_UeberN1, 1, 1, &data);
  sRecorded.actionMessage = eActionMessage_Act_TempRegler_HeizEin;
  if (!assertMessageAction(sRecorded,"TestEvent Evt_Kessel.UeberN1 [afb86e65-b78e-11ea-848b-a5c54ed864b3]","[afe300eb-b78e-11ea-848b-a5c54ed864b3]", "KesselTest" ,0)) {return 0;}
  if (!assertMessageActionCount("TestEvent Evt_Kessel.UeberN1 [afb86e65-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_Kessel_UeberN2, 1, 1, &data);
  sRecorded.actionMessage = eActionMessage_Act_Kessel_Leeren;
  if (!assertMessageAction(sRecorded,"TestEvent Evt_Kessel.UeberN2 [bdf8f548-b78e-11ea-848b-a5c54ed864b3]","[be04dc3b-b78e-11ea-848b-a5c54ed864b3]", "KesselTest" ,0)) {return 0;}
  if (!assertMessageActionCount("TestEvent Evt_Kessel.UeberN2 [bdf8f548-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_TempRegler_UeberT, 1, 1, &data);
  sRecorded.actionMessage = eActionMessage_Act_TempRegler_HeizAus;
  if (!assertMessageAction(sRecorded,"TestEvent Evt_TempRegler.UeberT [c42d3f61-b78e-11ea-848b-a5c54ed864b3]","[c436b553-b78e-11ea-848b-a5c54ed864b3]", "KesselTest" ,0)) {return 0;}
  if (!assertMessageActionCount("TestEvent Evt_TempRegler.UeberT [c42d3f61-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_TempRegler_UnterT, 1, 1, &data);
  sRecorded.actionMessage = eActionMessage_Act_TempRegler_HeizEin;
  if (!assertMessageAction(sRecorded,"TestEvent Evt_TempRegler.UnterT [c99781c6-b78e-11ea-848b-a5c54ed864b3]","[c9a368b6-b78e-11ea-848b-a5c54ed864b3]", "KesselTest" ,0)) {return 0;}
  if (!assertMessageActionCount("TestEvent Evt_TempRegler.UnterT [c99781c6-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_HauptSchalter_KesselAus, 1, 1, &data);
  if (!assertMessageActionCount("TestEvent Evt_HauptSchalter.KesselAus [d387e912-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_Kessel_UnterN2, 1, 1, &data);
  if (!assertMessageActionCount("TestEvent Evt_Kessel.UnterN2 [d796bb2a-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  
  sendMessageEvent(eEventMessage_Evt_Kessel_UnterN1, 1, 1, &data);
  sRecorded.actionMessage = eActionMessage_Act_TempRegler_HeizAus;
  if (!assertMessageAction(sRecorded,"TestEvent Evt_Kessel.UnterN1 [dbea5d6b-b78e-11ea-848b-a5c54ed864b3]","[dbf755cf-b78e-11ea-848b-a5c54ed864b3]", "KesselTest" ,0)) {return 0;}
  if (!assertMessageActionCount("TestEvent Evt_Kessel.UnterN1 [dbea5d6b-b78e-11ea-848b-a5c54ed864b3]", "KesselTest")) {return 0;}
  

  return 1;
}

/** 
 *  Write string to file.
 */
void printToFile(FILE *fp, const char* s) 
{
  if (fp == NULL) return;
  fprintf(fp, s);
}

/** 
 *  Regressive animation, controlled by test cases. 
 *  @return The number of failed test cases.
 */
int regressiveAnimation()
{
  printf("TESTING: CipTestSuite SystemEmbedded [4ae31ce4-2fda-11e2-a23a-331776341c66]\n\n"); 
  g_eAnimationMode = eAnimationMode_Regressive;
  int nSuceededTestCases = 0;
  int nFailedTestCases = 0;
  g_eTraceMode = eTrace_Enable;
  if (testCase_KesselTest(1)) {++nSuceededTestCases;} else {++nFailedTestCases;}
  printf("\n> SUMMARY: %i Test Case(s) Executed.\n",nSuceededTestCases+nFailedTestCases); 
  if (nFailedTestCases) {printf("> WARNING: %i Test Case(s) Failed.\n",nFailedTestCases);} 
  return nFailedTestCases;
}

/** 
 *  C/C++ Unit gtest, controlled by test cases. 
 *  @return The number of failed test cases.
 */
int runnerAnimation(FILE *fp)
{
  int nSuceededTestCases = 0;
  int nFailedTestCases = 0;
  g_eAnimationMode = eAnimationMode_Runner;
	  
  printf("[==========] Running 1 test from 1 test case.\n");
  printf("[----------] Global test environment set-up.\n");
  printf("[----------] 1 test from SystemEmbedded\n");
   
  printToFile(fp, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n");
  printToFile(fp, "<testsuite name=\"SystemEmbedded\">\n");
      	  
  /* KesselTest */
  g_eTraceMode = eTrace_Enable;
  printf("[ RUN      ] SystemEmbedded.KesselTest\n");
  if (testCase_KesselTest(1)) {
  	++nSuceededTestCases;
  	printf("[       OK ] SystemEmbedded.KesselTest (%i ms)\n",s_nSystemTick);
  	printToFile(fp, "    <testcase name=\"KesselTest\" status=\"run\" />\n");
  } else {
  	++nFailedTestCases;
	printf("[  FAILED  ] SystemEmbedded.KesselTest (%i ms)\n",s_nSystemTick);
	printToFile(fp, "    <testcase name=\"KesselTest\" status=\"run\">\n");
	printToFile(fp, "        <failure><![CDATA[Failure testcase: b0025141-e1c7-11e3-bb00-f724347870c1]]></failure>\n");
	printToFile(fp, "    </testcase>\n");
  }
	
  printToFile(fp, "</testsuite>");
  
  printf("[----------] 1 test from SystemEmbedded (0 ms total)\n");
  printf("\n> SUMMARY: %i Test Case(s) Executed.\n",nSuceededTestCases+nFailedTestCases); 
  if (nFailedTestCases) {
  	printf("> WARNING: %i Test Case(s) Failed.\n",nFailedTestCases);
  }
  printf("[----------] Global test environment tear-down\n");
  printf("[==========] 1 test from 1 test case ran. (0 ms total)\n");
  return nFailedTestCases;
}

/** 
 *  Manual animation, controlled by keyboard input. 
 *  @return 0 if exited normally. 1 otherwise.
 */
int manualAnimation()
{
  T_UEventData data;
  g_eAnimationMode = eAnimationMode_Manual;
  g_eTraceMode = eTrace_Enable;
  
  if (!fINIT_KesselUnit()) 
  {
    printf("\nInitialization failed\n");
    return 1;
  }
  
  while (1) 
  {
    printf("------------------------------------\n");
    printf("Enter -1 (Quit)\n");
    printf("Enter 0 (Tick  & TimeUp)\n");
    printf("Enter 1 (Step)\n");
    printf("Enter 2 (TimeUp)\n");
    printf("Enter 3 (Chain)\n");
    printf("Enter 4 (Read)\n");
    printf("Enter 5 (Auto)\n");
    printf("Enter  %i (Evt_HauptSchalter: KesselAus)\n",eEventMessage_Evt_HauptSchalter_KesselAus);
    printf("Enter  %i (Evt_HauptSchalter: KesselEin)\n",eEventMessage_Evt_HauptSchalter_KesselEin);
    printf("Enter  %i (Evt_Kessel: UeberN1)\n",eEventMessage_Evt_Kessel_UeberN1);
    printf("Enter  %i (Evt_Kessel: UeberN2)\n",eEventMessage_Evt_Kessel_UeberN2);
    printf("Enter  %i (Evt_Kessel: UnterN1)\n",eEventMessage_Evt_Kessel_UnterN1);
    printf("Enter  %i (Evt_Kessel: UnterN2)\n",eEventMessage_Evt_Kessel_UnterN2);
    printf("Enter  %i (Evt_TempRegler: UeberT)\n",eEventMessage_Evt_TempRegler_UeberT);
    printf("Enter  %i (Evt_TempRegler: UnterT)\n",eEventMessage_Evt_TempRegler_UnterT);
    printf("------------------------------------\n");

    T_EEventMessage eEventMessage;
    scanf("%i", (int*)&eEventMessage);
    if (eEventMessage == eEventMessage_Quit) {break;}
    else if (eEventMessage == eEventMessage_Tick) {
        data.tick = 1;
        sendMessageEvent(eEventMessage_Tick, 1, 1, &data);
    }
    else if (!sendMessageEvent(eEventMessage, 1, 1, &data)) {printf("\n Invalid Input: %i\n\n",eEventMessage);}
  }
  return 0;
}

/**************************************************
 * Visaul Animation
 **************************************************/

/** 
 *  Get EventData from the channel message.
 *  @return true or false.
 */
static int getEventData(t_TokensContext* tokenContext, T_EEventMessage eventMessage, T_UEventData *data)
{
  switch(eventMessage) 
  {
  case eEventMessage_Tick:
    if (MessageHandler_hasValue(tokenContext))
    {
      jsmntok_t token;
      int integer;
      if (!JsonUtl_getNextToken(tokenContext, &token)) return 0;
      if (!JsonUtl_getTokenInteger(token, tokenContext, &integer)) return 0;
      data->tick = integer;
    } 
    else 
    {
      data->tick = 1;
    }
    return 1;
  case eEventMessage_Step:
    return 1;	
  case eEventMessage_TimeUp:
    return 1;	
  case eEventMessage_Chain:
    return 1;
  case eEventMessage_Read:
    return 1;	
  case eEventMessage_Auto:
    return 1;
  case eEventMessage_Evt_HauptSchalter_KesselAus:
    return 1;
      break;
  case eEventMessage_Evt_HauptSchalter_KesselEin:
    return 1;
      break;
  case eEventMessage_Evt_Kessel_UeberN1:
    return 1;
      break;
  case eEventMessage_Evt_Kessel_UeberN2:
    return 1;
      break;
  case eEventMessage_Evt_Kessel_UnterN1:
    return 1;
      break;
  case eEventMessage_Evt_Kessel_UnterN2:
    return 1;
      break;
  case eEventMessage_Evt_TempRegler_UeberT:
    return 1;
      break;
  case eEventMessage_Evt_TempRegler_UnterT:
    return 1;
      break;
    default:
      break;
  }
  return 0;
}


/** 
 *  get the EventMessage by event id.
 *  @return true or false.
 */
static int getEventMessage(t_JsonId *eventId, T_EEventMessage *eventMessage)
{
  int subId = 0;
  if (eventId->idSize != 1) return 0;
  subId = eventId->id[0];
  if (eEventMessageCount <= subId || subId < 0) return 0;
  *eventMessage = (T_EEventMessage)subId;
  return 1;
}

/**
 *  Regressive animation, controlled by test cases.
 *  @return The number of failed test cases.
 */
int handleVisualAnimationJsonMessage(t_TokensContext* tokenContext, t_ConnectionContext* connection) 
{
  jsmntok_t token;
  t_ConnectionData *connectionData = MessageHandler_getConnectionData(connection);

  if (!JsonUtl_getNextToken(tokenContext, &token)) return False;
  if (!JsonUtl_isObject(token)) return False;
  if (!JsonUtl_getNextToken(tokenContext, &token)) return False;

  /* BIND */
  if (JsonUtl_equalsTokenString(token, tokenContext, TOKEN_BIND))
  {
    t_JsonId modulId;
    if (!MessageHandler_getBindId(tokenContext, &modulId)) return 0;
    connectionData->isBinded = 1;
    connectionData->bindId = modulId;
    MessageHandler_sendStartTypeHistory(connection, &modulId);
    MessageHandler_sendStartTypeSnapshot(connection, &modulId);
    fDUMP_KesselUnit();
    MessageHandler_sendStartTypeUpdate(connection, &modulId);
    return 1;
  }

  /* UNBIND */
  if (JsonUtl_equalsTokenString(token, tokenContext, TOKEN_UNBIND))
  {
    t_JsonId jsonId;
    if (!MessageHandler_getBindId(tokenContext, &jsonId)) return 0;
    t_ConnectionData *connectionData = MessageHandler_getConnectionData(connection);
    connectionData->isBinded = 0;
    connectionData->bindId = jsonId;
    return 1;
  }

  /* TOKEN_EXPLORER_TREE */
  if (JsonUtl_equalsTokenString(token, tokenContext, TOKEN_EXPLORER_TREE))
  { 
    return 1;
  }

  /* TOKEN_ERROR */
  if (JsonUtl_equalsTokenString(token, tokenContext, TOKEN_ERROR))
  {
    if (!fINIT_KesselUnit())
    {
      printf("Reset Cip-System \n");
    }
    return 1;
  }
  
  /* TOKEN_TEST_BENCH_STATE */
  if (JsonUtl_equalsTokenString(token, tokenContext, TOKEN_TEST_BENCH_STATE))
  {
    if (!MessageHandler_isResetRequest(tokenContext)) return 0;
    if (!fINIT_KesselUnit())
    {
      MessageHandler_sendErrorResponse(&s_connectionContext, "Cip Initialization failed.");
      return 0;
    }
    if (connectionData->isBinded)
    {
      MessageHandler_sendStartTypeHistory(connection, &connectionData->bindId);
      MessageHandler_sendStartTypeSnapshot(connection, &connectionData->bindId);
      fDUMP_KesselUnit();
      MessageHandler_sendStartTypeUpdate(connection, &connectionData->bindId);
    }
    printf("Reset Cip-System \n");
    MessageHandler_sendCompleteResponse(connection);
    return 1;
  }

  /* TOKEN_TEST_BENCH_EVENT */
  if (JsonUtl_equalsTokenString(token, tokenContext, TOKEN_TEST_BENCH_EVENT))
  {
    t_JsonId eventId;
    T_EEventMessage eventMessage;
    T_UEventData eventData;
 
    if (!MessageHandler_getTestBenchEventId(tokenContext, &eventId)) return 0;
    if (!getEventMessage(&eventId, &eventMessage))
    {
       MessageHandler_sendErrorResponse(&s_connectionContext, "Error: Event message id is invalide.");
       return 0;
    }

    if (!getEventData(tokenContext, eventMessage, &eventData)) 
    {
      MessageHandler_sendErrorResponse(&s_connectionContext, "Error: Pars event data.");
      return 0;
    }
    
    if (!sendMessageEvent(eventMessage, 1, 1, &eventData))
    {
      MessageHandler_sendErrorResponse(&s_connectionContext, "Error: Send message event.");
      return 0;
    }
    MessageHandler_sendCompleteResponse(connection);
    return 1;
  }
  return 0;
}

/**
 *  Regressive animation, controlled by test cases.
 *  @return The number of failed test cases.
 */
int visualAnimation()
{
  int failed = 0;// False
  char jsonMessage[500];
  char message[500];
  t_TokensContext tokenContext;
  t_ConnectionData connectionData;
  connectionData.isBinded = 0;
  connectionData.sequenceNumber = 0;
	  
  s_connectionContext.userData = &connectionData;
  g_eAnimationMode = eAnimationMode_Visual;

  printf("Start animation server port: %d ...", SERVER_PORT);
  if (!AnimationSocket_Start()) 
  {
    printf("Error \n");
    return 1;
  }
  printf(" Started\n");
  
  while (!failed) 
  {

    if (!s_connectionContext.connected) 
    {
      if (!AnimationSocket_AcceptClient(&s_connectionContext)) 
      {
        printf("Accept client fail. \n");
        failed = 1;
        break;
      }
      
      MessageHandler_sendLogInfoResponse(&s_connectionContext, "Client is connected to animation server.");

      if (!fINIT_KesselUnit())
      {
        MessageHandler_sendErrorResponse(&s_connectionContext, "Cip Initialization failed.");
        AnimationSocket_Close(&s_connectionContext);
        failed = 1;
        break;
      }
    }

    if (!JsonUtl_readMessage(&s_connectionContext, jsonMessage)) {
      MessageHandler_sendErrorResponse(&s_connectionContext, "Read message failed.");
      AnimationSocket_Close(&s_connectionContext);
      continue;
    }

    if (!JsonUtl_parsMessage(jsonMessage, &tokenContext)) 
    {
      JsonUtl_initStringBuffer(message);
      JsonUtl_appendString(message, "Pars json message failed: ");
      JsonUtl_appendString(message, jsonMessage);
      MessageHandler_sendErrorResponse(&s_connectionContext, message);
      failed = 1;
      break;
    }

    if (!handleVisualAnimationJsonMessage(&tokenContext, &s_connectionContext)) {
      MessageHandler_sendErrorResponse(&s_connectionContext, "Handle json message failed.");
    }
  }

  if (!AnimationSocket_Close(&s_connectionContext)) {
    MessageHandler_sendErrorResponse(&s_connectionContext, "Close socket failed.");
    failed = 1;
  }
  
  printf("Stop animation server port: %d ...", SERVER_PORT);
  return failed;
}

/** 
 *  Displays an info text for this program.
 *  @param i_pcProgramName The name of the program file.
 */
void displayInfoText(char* i_pcProgramName)
{
  printf("Usage: %s [option]\n",i_pcProgramName);
  printf(" [option]\n");
  printf(" - manual:     Manual animation, controlled by keyboard input.\n");
  printf(" - regressive: Regressive animation, controlled by test cases.\n");
  printf(" - runner [optional filename]: C/C++ Unit gtest.\n");
  printf(" - animation: Visual browser animation.\n");
}

/**
 *  Main program for animation.
 *  @param @argc The number of arguments passed to the program.
 *  @param @argv The arguments passed to the program.
 *  @return 0 if exited normally. 1 otherwise.
 */
int main(int argc, char *argv[]) 
{
  int ret;
  if (argc == 1) 
  {
    displayInfoText(argv[0]);
    return 1;
  }

  if (strcmp(argv[1],"manual")==0) 
  {
    ret = manualAnimation()?1:0;
    return ret;
  }
  if (strcmp(argv[1],"regressive")==0) 
  {
    ret = regressiveAnimation()?1:0;
    return ret;
  }
  if (strcmp(argv[1],"runner")==0) 
  {
    FILE *fp = NULL;
    if (argc >= 2) {
        fp = fopen(argv[2], "w+");
    }
    ret = runnerAnimation(fp)?1:0;
    if (fp != NULL) {
        fclose(fp);
    }
    return ret;
  }
  if (strcmp(argv[1],"animation")==0)
  {
	ret = visualAnimation()?1:0;
	return ret;
  }
  displayInfoText(argv[0]);
  return 1;
}

/* Actifsource ID=[bc0af8c6-407d-11e2-9941-ff65f3a86106,4ae31ce4-2fda-11e2-a23a-331776341c66,p4gFFNWEGyavkX3DXr3VaowY3bE=] */
