/*********************************************************************
	SYSTEM Kesselsteuerung_Loesung
	IMPLEMENTATION implementation
	Module for CIP MACHINE mKesselUnit
	Filename: mKesselUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mKesselUnit.h"
#include "tKesselUnit.h"

/* External Declarations */

void fIMSG_C2_KesselAus(void);
void fIMSG_C2_KesselEin(void);
void fIMSG_C3_UeberN1(void);
void fIMSG_C3_UeberN2(void);
void fIMSG_C3_UnterN1(void);
void fIMSG_C3_UnterN2(void);
void fIMSG_C5_UeberT(void);
void fIMSG_C5_UnterT(void);
void fINIT_Kessel (void);
void fINIT_Schalter (void);
void fINIT_TempRegler (void);
void fDUMP_Kessel (void);
void fDUMP_Schalter (void);
void fDUMP_TempRegler (void);

/* Global Declarations */

unsigned long time_KesselUnit = 0;
struct tCHNOUT_mKesselUnit CHNOUT_mKesselUnit;

/* Function Prototypes */

void fSTEP_KesselUnit(void);
void fCHAIN_KesselUnit(void);
void fTIMEUP_KesselUnit(void);
void fREAD_KesselUnit(void);

/* AUTO_ Handler Function */

static void fAUTOHDL_KesselUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_KesselUnit(void)
{
	++time_KesselUnit;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_KesselUnit(void)
{
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_KesselUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_KesselUnit(void)
{
	return;
}

	/* Read Function for CIP Machine */

void fREAD_KesselUnit(void)
{
	return;
}


/* Initialization Function */

int fDUMP_KesselUnit(void)
{
	fDUMP_Kessel();
	fDUMP_Schalter();
	fDUMP_TempRegler();
 	return 1;
}

/* Initialization Function */

int fINIT_KesselUnit(void)
{
	TRG_KesselUnit.TICK_ = fTICK_KesselUnit;
	TRG_KesselUnit.CHAIN_ = fCHAIN_KesselUnit;
	TRG_KesselUnit.TIMEUP_ = fTIMEUP_KesselUnit;
	TRG_KesselUnit.STEP_ = fSTEP_KesselUnit;
	TRG_KesselUnit.READ_ = fREAD_KesselUnit;
	TRG_KesselUnit.AUTO_ = fAUTOHDL_KesselUnit;
	IN_KesselUnit.C2_KesselAus = fIMSG_C2_KesselAus;
	IN_KesselUnit.C2_KesselEin = fIMSG_C2_KesselEin;
	IN_KesselUnit.C3_UeberN1 = fIMSG_C3_UeberN1;
	IN_KesselUnit.C3_UeberN2 = fIMSG_C3_UeberN2;
	IN_KesselUnit.C3_UnterN1 = fIMSG_C3_UnterN1;
	IN_KesselUnit.C3_UnterN2 = fIMSG_C3_UnterN2;
	IN_KesselUnit.C5_UeberT = fIMSG_C5_UeberT;
	IN_KesselUnit.C5_UnterT = fIMSG_C5_UnterT;
	iMSG_KesselUnit();
	if (!OUT_KesselUnit.C4_Fuellen)
	{
		return 0;
	}
	if (!OUT_KesselUnit.C4_Leeren)
	{
		return 0;
	}
	if (!OUT_KesselUnit.C6_HeizAus)
	{
		return 0;
	}
	if (!OUT_KesselUnit.C6_HeizEin)
	{
		return 0;
	}
	iTRACE_KesselUnit();
	if (!TRACE_KesselUnit.DUMP_)
	{
		return 0;
	}
	if (!TRACE_KesselUnit.CHANGE_)
	{
		return 0;
	}
	fINIT_Kessel ();
	fINIT_Schalter ();
	fINIT_TempRegler ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mKesselUnit
*********************************************************************/

/* Actifsource ID=[a9fcef86-9d17-11e1-90e4-e1fd5739c0f6,304ffac5-2fda-11e2-a23a-331776341c66,5b61a23d-2fd9-11e2-a23a-331776341c66,21741d8a-2fda-11e2-a23a-331776341c66,305244be-2fda-11e2-a23a-331776341c66,305244b9-2fda-11e2-a23a-331776341c66,/cvgDwLK/D0hxyINBjbfLJCAhlU=] */
