/*********************************************************************
	SYSTEM Kesselsteuerung_Loesung
	IMPLEMENTATION implementation
	Header File for CIP MACHINE mKesselUnit
	Filename: mKesselUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_mKesselUnit_hKesselUnit_)
	#define _mKesselUnit_hKesselUnit_

/* Include Files */

#include <stdlib.h>
#include "sKesselUnit.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Outpulse Types */
 
#if !defined(_eOUTPLS_KesselUnit_)
	#define _eOUTPLS_KesselUnit_

	enum eOUTPLS_KesselUnit
		{/* KesselSteuerung */ O4_startTR = 1, O4_stopTR, O3_start};

#endif // _eOUTPLS_KesselUnit_

struct tOUTPLS_Kessel
{
	enum eOUTPLS_KesselUnit name_;
};

struct tOUTPLS_Schalter
{
	enum eOUTPLS_KesselUnit name_;
};

union tOUTPLS_KesselSteuerung
{
	struct tOUTPLS_Kessel OUTPLS_Kessel;
	struct tOUTPLS_Schalter OUTPLS_Schalter;
};

/* Global Output Type */

struct tCHAN_Act_Kessel
{
	enum eMSG_Act_Kessel name_;
};

struct tCHAN_Act_TempRegler
{
	enum eMSG_Act_TempRegler name_;
};

union tCHAN_mKesselUnit
{
	struct tCHAN_Act_Kessel CHAN_Act_Kessel;
	struct tCHAN_Act_TempRegler CHAN_Act_TempRegler;
};

struct tCHNOUT_mKesselUnit
{
	union tCHAN_mKesselUnit message_;
};

/* Types for Process Kessel */

struct tPRSTAT_Kessel
{
	int STATE;
	int MODE;
	int anzahlZyklen;
	int zaehler;
};

union tSTATUS_Kessel
{
	struct tPRSTAT_Kessel write_access_;
	struct tPRSTAT_Kessel read_access_;
};

/* Types for Process Schalter */

struct tPRSTAT_Schalter
{
	int STATE;
	int MODE;
};

union tSTATUS_Schalter
{
	struct tPRSTAT_Schalter write_access_;
	struct tPRSTAT_Schalter read_access_;
};

/* Types for Process TempRegler */

struct tPRSTAT_TempRegler
{
	int STATE;
	int MODE;
};

union tSTATUS_TempRegler
{
	struct tPRSTAT_TempRegler write_access_;
	struct tPRSTAT_TempRegler read_access_;
};

#endif // _mKesselUnit_hKesselUnit_

/*********************************************************************
	End of Header File for CIP MACHINE mKesselUnit
*********************************************************************/
/* Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,304ffac5-2fda-11e2-a23a-331776341c66,5b61a23d-2fd9-11e2-a23a-331776341c66,21741d8a-2fda-11e2-a23a-331776341c66,305244be-2fda-11e2-a23a-331776341c66,305244b9-2fda-11e2-a23a-331776341c66,IReJsLqFcmoiLnphFSX1oNlP8cc=] */
