/*********************************************************************
	SYSTEM Kesselsteuerung_Loesung
	IMPLEMENTATION implementation
	Module for CIP SHELL sKesselUnit
	Filename: sKesselUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "sKesselUnit.h"

/* Input Interface */

struct tIN_KesselUnit IN_KesselUnit;

/* Output Interface */

struct tOUT_KesselUnit OUT_KesselUnit;

/* Trigger Interface */

struct tTRG_KesselUnit TRG_KesselUnit;

/*********************************************************************
	End of Module for CIP SHELL sKesselUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,304ffac5-2fda-11e2-a23a-331776341c66,5b61a23d-2fd9-11e2-a23a-331776341c66,21741d8a-2fda-11e2-a23a-331776341c66,305244b9-2fda-11e2-a23a-331776341c66,305244be-2fda-11e2-a23a-331776341c66,n2KsFVGGfUjslnyGyDbJ2897UKQ=] */
