/*********************************************************************
	SYSTEM Kesselsteuerung
	IMPLEMENTATION Kessel
	Error Interface Module for CIP MACHINE mKesselUnit
	Filename: eKesselUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "eKesselUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mKesselUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,c511814e-37d0-11e2-9d61-05c638030bc3,4bc43bb6-2fdf-11e2-a23a-331776341c66,cb79ac2d-37d0-11e2-9d61-05c638030bc3,c5166352-37d0-11e2-9d61-05c638030bc3,w+Ub7zlE6OJ3FLEXEs/VPZlRdh4=] */
