/*******************************************************************
        SYSTEM Kesselsteuerung
        Module for PROCESS Kessel
        Filename: Kessel.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		KesselUnit 
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mKesselUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Kessel.write_access_
#define STATUS (pStatus_Kessel->read_access_)
#define TIME time_KesselUnit

/* Process Enumerations */

enum eMODES_Kessel
	{normal = 1};

enum eSTATES_Kessel
	{leer = 1, leerFuellend, tlwVollFuellend, tlwVollLeerend, vollLeerend};


/* External Declarations */

extern unsigned char time_KesselUnit;
extern struct tCHNOUT_mKesselUnit CHNOUT_mKesselUnit;

/* Global Declarations */

union tSTATUS_Kessel status_Kessel;
const union tSTATUS_Kessel *pStatus_Kessel = &status_Kessel;

/* Function Prototypes */

void fIMSG_C3_UeberN1(void);
void fIMSG_C3_UeberN2(void);
void fIMSG_C3_UnterN1(void);
void fIMSG_C3_UnterN2(void);
void fINIT_Kessel (void);

/* Input Channel Functions */

void fIMSG_C3_UeberN1(void)
{
	return;
}

void fIMSG_C3_UeberN2(void)
{
	return;
}

void fIMSG_C3_UnterN1(void)
{
	return;
}

void fIMSG_C3_UnterN2(void)
{
	return;
}
		
/* Process Initialization Function */

void fINIT_Kessel (void)
{
	status_Kessel.write_access_.STATE = leer;
}		

/*********************************************************************
	End of Module for PROCESS Kessel
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,c511814e-37d0-11e2-9d61-05c638030bc3,4bc43bb6-2fdf-11e2-a23a-331776341c66,cb79ac2d-37d0-11e2-9d61-05c638030bc3,c5166352-37d0-11e2-9d61-05c638030bc3,4bc68603-2fdf-11e2-a23a-331776341c66,4bc68607-2fdf-11e2-a23a-331776341c66,xK+vMswszi+Kc3boYpsWemm1Rbs=] */
