/*******************************************************************
        SYSTEM Kesselsteuerung
        Module for PROCESS Schalter
        Filename: Schalter.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		KesselUnit 
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mKesselUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Schalter.write_access_
#define STATUS (pStatus_Schalter->read_access_)
#define TIME time_KesselUnit

/* Process Enumerations */

enum eMODES_Schalter
	{normal = 1};

enum eSTATES_Schalter
	{Aus = 1, Ein};


/* External Declarations */

extern unsigned char time_KesselUnit;
extern struct tCHNOUT_mKesselUnit CHNOUT_mKesselUnit;

/* Global Declarations */

union tSTATUS_Schalter status_Schalter;
const union tSTATUS_Schalter *pStatus_Schalter = &status_Schalter;

/* Function Prototypes */

void fIMSG_C2_KesselAus(void);
void fIMSG_C2_KesselEin(void);
void fINIT_Schalter (void);

/* Input Channel Functions */

void fIMSG_C2_KesselAus(void)
{
	switch(status_Schalter.read_access_.STATE)
	{
	case Ein:
	 	status_Schalter.write_access_.STATE = Aus;
		break;
	default:
		return;
	}
	return;
}

void fIMSG_C2_KesselEin(void)
{
	switch(status_Schalter.read_access_.STATE)
	{
	case Aus:
	 	status_Schalter.write_access_.STATE = Ein;
		break;
	default:
		return;
	}
	return;
}
		
/* Process Initialization Function */

void fINIT_Schalter (void)
{
	status_Schalter.write_access_.STATE = Aus;
}		

/*********************************************************************
	End of Module for PROCESS Schalter
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,c511814e-37d0-11e2-9d61-05c638030bc3,4bc43bb6-2fdf-11e2-a23a-331776341c66,cb79ac2d-37d0-11e2-9d61-05c638030bc3,c5166352-37d0-11e2-9d61-05c638030bc3,4bc68603-2fdf-11e2-a23a-331776341c66,4bc8f663-2fdf-11e2-a23a-331776341c66,Ljm0ygoXEQXkrVtgqVPPKFVnrDE=] */
