/*********************************************************************
	SYSTEM Kesselsteuerung
	IMPLEMENTATION Kessel
	Module for CIP SHELL sKesselUnit
	Filename: sKesselUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			KesselUnit 
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "sKesselUnit.h"

/* Input Interface */

struct tIN_KesselUnit IN_KesselUnit;

/* Output Interface */

struct tOUT_KesselUnit OUT_KesselUnit;

/* Trigger Interface */

struct tTRG_KesselUnit TRG_KesselUnit;

/*********************************************************************
	End of Module for CIP SHELL sKesselUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,c511814e-37d0-11e2-9d61-05c638030bc3,4bc43bb6-2fdf-11e2-a23a-331776341c66,cb79ac2d-37d0-11e2-9d61-05c638030bc3,c5166352-37d0-11e2-9d61-05c638030bc3,c5166357-37d0-11e2-9d61-05c638030bc3,7lInqYnZFaQiXEUAD2K9thgcY6A=] */
