/*******************************************************************
        SYSTEM ClusterGroup_System_Library
        Module for PROCESS Button_D
        Filename: Button_D.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use channel interface
        		naming option: use default prefix
        	use postfix
        		 LampUnit_HANS
        	enable mode inspection
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mLampUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Button_D_HANS.write_access_
#define STATUS (pStatus_Button_D_HANS->read_access_)
#define TIME time_LampUnit_HANS

/* Process Enumerations */

enum eMODES_Button_D
	{normal = 1};

enum eSTATES_Button_D
	{pushed = 1, released};


/* External Declarations */

extern unsigned long time_LampUnit_HANS;
extern struct tCHNOUT_mLampUnit_HANS CHNOUT_mLampUnit_HANS;
int fPULSE_Lamp_D_HANS (enum eOUTPLS_LampUnit_HANS name_);

/* Global Declarations */

union tSTATUS_Button_D_HANS status_Button_D_HANS;
const union tSTATUS_Button_D_HANS *pStatus_Button_D_HANS = &status_Button_D_HANS;

/* Function Prototypes */

void fICHAN_ButtonEvents9_HANS (enum eMSG_ButtonEvents9_HANS name_);
void fINIT_Button_D_HANS (void);

/* Input Channel Functions */

void fICHAN_ButtonEvents9_HANS(enum eMSG_ButtonEvents9_HANS name_)
{
	switch(name_)
	{
		/* MESSAGE Push of INPORT EVENT_PORT */
	case C18_Push:
		switch(status_Button_D_HANS.read_access_.STATE)
		{
		case released:
		 	status_Button_D_HANS.write_access_.STATE = pushed;
		 	fPULSE_Lamp_D_HANS (O1_on);
			break;
		default:
			return;
		}		
		break;
		/* MESSAGE Release of INPORT EVENT_PORT */
	case C18_Release:
		switch(status_Button_D_HANS.read_access_.STATE)
		{
		case pushed:
		 	status_Button_D_HANS.write_access_.STATE = released;
		 	fPULSE_Lamp_D_HANS (O1_off);
			break;
		default:
			return;
		}		
		break;
	default:
		return;
	}
	return;
}
		
/* Process Initialization Function */

void fINIT_Button_D_HANS (void)
{
	status_Button_D_HANS.write_access_.MODE = normal;
	status_Button_D_HANS.write_access_.STATE = released;
}		

/*********************************************************************
	End of Module for PROCESS Button_D
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,84174139-b789-11ea-9e22-1112d6355503,84174105-b789-11ea-9e22-1112d6355503,OuqN4Q6l5SUaSD05hKR13jWA8Qg=] */
