/*********************************************************************
	SYSTEM ClusterGroup_System_Library
	IMPLEMENTATION LampImpl
	Error Interface Module for CIP MACHINE mLampUnit
	Filename: eLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "eLampUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,MDhc6CRjcbPuwwsR5SOoyGewGz0=] */
