/*******************************************************************
        SYSTEM ClusterGroup_System_Library
        Module for PROCESS Lamp_D
        Filename: Lamp_D.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use channel interface
        		naming option: use default prefix
        	use postfix
        		 LampUnit_HANS
        	enable mode inspection
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mLampUnit.h"

/* Process Macro Definitions */

#define SELF status_Lamp_D_HANS.write_access_
#define STATUS (pStatus_Lamp_D_HANS->read_access_)
#define TIME time_LampUnit_HANS

/* Process Enumerations */

enum eMODES_Lamp_D
	{normal = 1};

enum eSTATES_Lamp_D
	{delayed = 1, off_, on_};

enum eINPULS_Lamp_D
	{IP_on = 1, IP_off = 2, TIMEUP_ = 3};
	

/* External Declarations */

extern unsigned long time_LampUnit_HANS;
extern struct tTMQE_mLampUnit_HANS *tuhead_mLampUnit_HANS, *tutail_mLampUnit_HANS;
extern struct tCHNOUT_mLampUnit_HANS CHNOUT_mLampUnit_HANS;
extern struct tTIMING_mLampUnit TIMING_mLampUnit_HANS[9];
void fSETTIM_mLampUnit_HANS (unsigned long *delay_, struct tTMEL_mLampUnit_HANS *timer_, struct tTMQE_mLampUnit_HANS *timeup_);
void fSTOPTIM_mLampUnit_HANS (struct tTMEL_mLampUnit_HANS *timer_, struct tTMQE_mLampUnit_HANS *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Lamp_D_HANS IO_Lamp_D_HANS;
union tSTATUS_Lamp_D_HANS status_Lamp_D_HANS;
const union tSTATUS_Lamp_D_HANS *pStatus_Lamp_D_HANS = &status_Lamp_D_HANS;

/* Function Prototypes */

int fPULSE_Lamp_D_HANS (enum eOUTPLS_LampUnit_HANS name_);
void fINIT_Lamp_D_HANS (void);

/* Input Channel Functions */

int fPULSE_Lamp_D_HANS (enum eOUTPLS_LampUnit_HANS name_)
{
	switch(name_)
	{
		/* INPULSE off */
	case O1_off:		/* PULSE CAST from PROCESS Button_D */
		switch(status_Lamp_D_HANS.read_access_.STATE)
		{
		case on_:
			{
				delay_ =  3;	/* DELAY DELAY_OPERATION */
				status_Lamp_D_HANS.write_access_.STATE = delayed;
				fSETTIM_mLampUnit_HANS(&delay_, 
					&IO_Lamp_D_HANS.timer_, 
					&IO_Lamp_D_HANS.timeup_);
			}
			break;
		default:
			break;
		}
		break;
		/* INPULSE on */
	case O1_on:		/* PULSE CAST from PROCESS Button_D */
		switch(status_Lamp_D_HANS.read_access_.STATE)
		{
		case delayed:
			{
				delay_ =  3;	/* DELAY DELAY_OPERATION */
				status_Lamp_D_HANS.write_access_.STATE = on_;
				fSETTIM_mLampUnit_HANS(&delay_, 
					&IO_Lamp_D_HANS.timer_, 
					&IO_Lamp_D_HANS.timeup_);
			}
			break;
		case off_:
			status_Lamp_D_HANS.write_access_.STATE = on_;
			CHNOUT_mLampUnit_HANS.message_.CHAN_LampActions9.name_ = C17_Bright;
			OUT_LampUnit_HANS.LampActions9(CHNOUT_mLampUnit_HANS.message_.CHAN_LampActions9.name_);
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Lamp_D_HANS (void)
{
	if (IO_Lamp_D_HANS.timer_.set_ &&
		IO_Lamp_D_HANS.timer_.end_ == time_LampUnit_HANS)
	{
		IO_Lamp_D_HANS.timer_.set_ = FALSE;
		--TIMING_mLampUnit_HANS[8].set_;
		if (tuhead_mLampUnit_HANS != &IO_Lamp_D_HANS.timeup_ &&
			!IO_Lamp_D_HANS.timeup_.preced_ &&
			!IO_Lamp_D_HANS.timeup_.next_)
		{
			if (!tuhead_mLampUnit_HANS)
			{
				tuhead_mLampUnit_HANS = tutail_mLampUnit_HANS = &IO_Lamp_D_HANS.timeup_;
			}
			else
			{
				tutail_mLampUnit_HANS->next_ = &IO_Lamp_D_HANS.timeup_;
				IO_Lamp_D_HANS.timeup_.preced_ = tutail_mLampUnit_HANS;
				tutail_mLampUnit_HANS = &IO_Lamp_D_HANS.timeup_;
			}
		}
	}			
}

static void fTUHNDL_Lamp_D(void)
{
	struct tTMQE_mLampUnit_HANS *element_ = tuhead_mLampUnit_HANS;
	if (tuhead_mLampUnit_HANS == tutail_mLampUnit_HANS)
	{
		tuhead_mLampUnit_HANS = tutail_mLampUnit_HANS = 0;
	}
	else 
	{
		tuhead_mLampUnit_HANS = element_->next_;
		element_->next_ = 0;
		tuhead_mLampUnit_HANS->preced_ = 0;
	}
	switch(status_Lamp_D_HANS.read_access_.STATE)
	{
	case delayed:
		status_Lamp_D_HANS.write_access_.STATE = off_;
		CHNOUT_mLampUnit_HANS.message_.CHAN_LampActions9.name_ = C17_Dark;
		OUT_LampUnit_HANS.LampActions9(CHNOUT_mLampUnit_HANS.message_.CHAN_LampActions9.name_);
		break;
	default:
		break;
	}
}

/* Process Initialization Function */

void fINIT_Lamp_D_HANS (void)
{
	status_Lamp_D_HANS.write_access_.MODE = normal;
	status_Lamp_D_HANS.write_access_.STATE = off_;
	IO_Lamp_D_HANS.timer_.set_ = FALSE;
	IO_Lamp_D_HANS.timeup_.preced_ = 0;
	IO_Lamp_D_HANS.timeup_.next_ = 0;
	IO_Lamp_D_HANS.timeup_.proctype_ = 8;
	TIMING_mLampUnit_HANS[8].tkhndl_ = fTICK_Lamp_D_HANS;
	TIMING_mLampUnit_HANS[8].tuhndl_ = fTUHNDL_Lamp_D;
}		

/*********************************************************************
	End of Module for PROCESS Lamp_D
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,84174139-b789-11ea-9e22-1112d6355503,84174122-b789-11ea-9e22-1112d6355503,itLFJFYPO+mDqQf2RQ3RvUjK1OQ=] */
