/*********************************************************************
	SYSTEM ClusterGroup_System_Library
	IMPLEMENTATION LampImpl
	Header File for CIP MACHINE mLampUnit
	Filename: mLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_mLampUnit_hLampUnit_HANS_)
	#define _mLampUnit_hLampUnit_HANS_

/* Include Files */

#include <stdlib.h>
#include "sLampUnit.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Constants */

#define Constant_CipSystem 56
#define Constant_CipSystemLib 56
#define Constant_SupperLib 56
#define Constant_GroupLib 56
#define Constant_ProcessLib 56
#define Constant_Group 56
#define Constant_Process 56

/* User Types */

typedef int UserType_CipSystem;

typedef int UserType_Group;

typedef int UserType_Process;

typedef int UserType_CipSystemLib;

typedef int Type_CipSystemLib;

typedef int UserType_SupperLib;

typedef int Type_SupperLib;

typedef int UserType_GroupLib;

typedef int Type_GroupLib;

typedef int UserType_ProcessLib;

typedef int Type_ProcessLib;

/* CIP Records */

#if !defined(_tCIPREC_RecordType_CipSystem_)
	#define _tCIPREC_RecordType_CipSystem_

	struct tCIPREC_RecordType_CipSystem
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_CipSystem_

#if !defined(_tCIPREC_RecordType_Group_)
	#define _tCIPREC_RecordType_Group_

	struct tCIPREC_RecordType_Group
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_Group_

#if !defined(_tCIPREC_RecordType_Process_)
	#define _tCIPREC_RecordType_Process_

	struct tCIPREC_RecordType_Process
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_Process_

#if !defined(_tCIPREC_RecordType_CipSystemLib_)
	#define _tCIPREC_RecordType_CipSystemLib_

	struct tCIPREC_RecordType_CipSystemLib
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_CipSystemLib_

#if !defined(_tCIPREC_RecordType_SupperLib_)
	#define _tCIPREC_RecordType_SupperLib_

	struct tCIPREC_RecordType_SupperLib
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_SupperLib_

#if !defined(_tCIPREC_RecordType_GroupLib_)
	#define _tCIPREC_RecordType_GroupLib_

	struct tCIPREC_RecordType_GroupLib
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_GroupLib_

#if !defined(_tCIPREC_RecordType_ProcessLib_)
	#define _tCIPREC_RecordType_ProcessLib_

	struct tCIPREC_RecordType_ProcessLib
	{
		char f1; 
	};

#endif // _tCIPREC_RecordType_ProcessLib_

/* Outpulse Types */
 
#if !defined(_eOUTPLS_LampUnit_HANS_)
	#define _eOUTPLS_LampUnit_HANS_

	enum eOUTPLS_LampUnit_HANS
		{/* Cluster_D */ O1_off = 1, O1_on, /* Cluster_A */ O4_off = 1, O4_on, O6_off, 
		 O6_on, O8_off, O8_on, O10_off, O10_on, /* Cluster_B */ O13_off = 1, O13_on, 
		 O15_off, O15_on, O17_off, O17_on, O19_off, O19_on};

#endif // _eOUTPLS_LampUnit_HANS_

struct tOUTPLS_Button_D_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

union tOUTPLS_Cluster_D_HANS
{
	struct tOUTPLS_Button_D_HANS OUTPLS_Button_D;
};

struct tOUTPLS_GroupA_Button_C_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

struct tOUTPLS_GroupA_Button_A_C_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

struct tOUTPLS_GroupA_Button_A_B_C1_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

struct tOUTPLS_GroupA_Button_A_B_C2_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

union tOUTPLS_Cluster_A_HANS
{
	struct tOUTPLS_GroupA_Button_C_HANS OUTPLS_GroupA_Button_C;
	struct tOUTPLS_GroupA_Button_A_C_HANS OUTPLS_GroupA_Button_A_C;
	struct tOUTPLS_GroupA_Button_A_B_C1_HANS OUTPLS_GroupA_Button_A_B_C1;
	struct tOUTPLS_GroupA_Button_A_B_C2_HANS OUTPLS_GroupA_Button_A_B_C2;
};

struct tOUTPLS_GroupB_Button_C_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

struct tOUTPLS_GroupB_Button_A_C_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

struct tOUTPLS_GroupB_Button_A_B_C1_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

struct tOUTPLS_GroupB_Button_A_B_C2_HANS
{
	enum eOUTPLS_LampUnit_HANS name_;
};

union tOUTPLS_Cluster_B_HANS
{
	struct tOUTPLS_GroupB_Button_C_HANS OUTPLS_GroupB_Button_C;
	struct tOUTPLS_GroupB_Button_A_C_HANS OUTPLS_GroupB_Button_A_C;
	struct tOUTPLS_GroupB_Button_A_B_C1_HANS OUTPLS_GroupB_Button_A_B_C1;
	struct tOUTPLS_GroupB_Button_A_B_C2_HANS OUTPLS_GroupB_Button_A_B_C2;
};

/* Global Output Type */

struct tCHAN_LampActions_HANS
{
	enum eMSG_LampActions_HANS name_;
};

struct tCHAN_LampActions2_HANS
{
	enum eMSG_LampActions2_HANS name_;
};

struct tCHAN_LampActions3_HANS
{
	enum eMSG_LampActions3_HANS name_;
};

struct tCHAN_LampActions4_HANS
{
	enum eMSG_LampActions4_HANS name_;
};

struct tCHAN_LampActions5_HANS
{
	enum eMSG_LampActions5_HANS name_;
};

struct tCHAN_LampActions6_HANS
{
	enum eMSG_LampActions6_HANS name_;
};

struct tCHAN_LampActions7_HANS
{
	enum eMSG_LampActions7_HANS name_;
};

struct tCHAN_LampActions8_HANS
{
	enum eMSG_LampActions8_HANS name_;
};

struct tCHAN_LampActions9_HANS
{
	enum eMSG_LampActions9_HANS name_;
};

union tCHAN_mLampUnit_HANS
{
	struct tCHAN_LampActions_HANS CHAN_LampActions;
	struct tCHAN_LampActions2_HANS CHAN_LampActions2;
	struct tCHAN_LampActions3_HANS CHAN_LampActions3;
	struct tCHAN_LampActions4_HANS CHAN_LampActions4;
	struct tCHAN_LampActions5_HANS CHAN_LampActions5;
	struct tCHAN_LampActions6_HANS CHAN_LampActions6;
	struct tCHAN_LampActions7_HANS CHAN_LampActions7;
	struct tCHAN_LampActions8_HANS CHAN_LampActions8;
	struct tCHAN_LampActions9_HANS CHAN_LampActions9;
};

struct tCHNOUT_mLampUnit_HANS
{
	union tCHAN_mLampUnit_HANS message_;
};

/* Timer- and Queue-Element */

struct tTMEL_mLampUnit_HANS
{
	unsigned char set_; /* Boolean */
	unsigned long end_;
};

struct tTMQE_mLampUnit_HANS
{
	struct tTMQE_mLampUnit_HANS *preced_;
	struct tTMQE_mLampUnit_HANS *next_;
	int proctype_;
};

/* Global Table Elements */
struct tTIMING_mLampUnit
{
	void  (*tkhndl_) (void);
	void (*tuhndl_)(void);
	int  set_;
};

/* Types for Process Button_D */

struct tPRSTAT_Button_D_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_Button_D_HANS
{
	struct tPRSTAT_Button_D_HANS write_access_;
	struct tPRSTAT_Button_D_HANS read_access_;
};

/* Types for Process Lamp_D */

struct tPRSTAT_Lamp_D_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_Lamp_D_HANS
{
	struct tPRSTAT_Lamp_D_HANS write_access_;
	struct tPRSTAT_Lamp_D_HANS read_access_;
};

struct tPRINST_Lamp_D_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupA_Button_C */

struct tPRSTAT_GroupA_Button_C_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupA_Button_C_HANS
{
	struct tPRSTAT_GroupA_Button_C_HANS write_access_;
	struct tPRSTAT_GroupA_Button_C_HANS read_access_;
};

/* Types for Process GroupA_Lamp_C */

struct tPRSTAT_GroupA_Lamp_C_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupA_Lamp_C_HANS
{
	struct tPRSTAT_GroupA_Lamp_C_HANS write_access_;
	struct tPRSTAT_GroupA_Lamp_C_HANS read_access_;
};

struct tPRINST_GroupA_Lamp_C_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupA_Button_A_C */

struct tPRSTAT_GroupA_Button_A_C_HANS
{
	int STATE;
	int MODE;
	double var_1;
};

union tSTATUS_GroupA_Button_A_C_HANS
{
	struct tPRSTAT_GroupA_Button_A_C_HANS write_access_;
	struct tPRSTAT_GroupA_Button_A_C_HANS read_access_;
};

/* Types for Process GroupA_Lamp_A_C */

struct tPRSTAT_GroupA_Lamp_A_C_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupA_Lamp_A_C_HANS
{
	struct tPRSTAT_GroupA_Lamp_A_C_HANS write_access_;
	struct tPRSTAT_GroupA_Lamp_A_C_HANS read_access_;
};

struct tPRINST_GroupA_Lamp_A_C_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupA_Button_A_B_C1 */

struct tPRSTAT_GroupA_Button_A_B_C1_HANS
{
	int STATE;
	int MODE;
	double var_1;
};

union tSTATUS_GroupA_Button_A_B_C1_HANS
{
	struct tPRSTAT_GroupA_Button_A_B_C1_HANS write_access_;
	struct tPRSTAT_GroupA_Button_A_B_C1_HANS read_access_;
};

/* Types for Process GroupA_Lamp_A_B_C1 */

struct tPRSTAT_GroupA_Lamp_A_B_C1_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupA_Lamp_A_B_C1_HANS
{
	struct tPRSTAT_GroupA_Lamp_A_B_C1_HANS write_access_;
	struct tPRSTAT_GroupA_Lamp_A_B_C1_HANS read_access_;
};

struct tPRINST_GroupA_Lamp_A_B_C1_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupA_Button_A_B_C2 */

struct tPRSTAT_GroupA_Button_A_B_C2_HANS
{
	int STATE;
	int MODE;
	double var_1;
};

union tSTATUS_GroupA_Button_A_B_C2_HANS
{
	struct tPRSTAT_GroupA_Button_A_B_C2_HANS write_access_;
	struct tPRSTAT_GroupA_Button_A_B_C2_HANS read_access_;
};

/* Types for Process GroupA_Lamp_A_B_C2 */

struct tPRSTAT_GroupA_Lamp_A_B_C2_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupA_Lamp_A_B_C2_HANS
{
	struct tPRSTAT_GroupA_Lamp_A_B_C2_HANS write_access_;
	struct tPRSTAT_GroupA_Lamp_A_B_C2_HANS read_access_;
};

struct tPRINST_GroupA_Lamp_A_B_C2_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupB_Button_C */

struct tPRSTAT_GroupB_Button_C_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupB_Button_C_HANS
{
	struct tPRSTAT_GroupB_Button_C_HANS write_access_;
	struct tPRSTAT_GroupB_Button_C_HANS read_access_;
};

/* Types for Process GroupB_Lamp_C */

struct tPRSTAT_GroupB_Lamp_C_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupB_Lamp_C_HANS
{
	struct tPRSTAT_GroupB_Lamp_C_HANS write_access_;
	struct tPRSTAT_GroupB_Lamp_C_HANS read_access_;
};

struct tPRINST_GroupB_Lamp_C_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupB_Button_A_C */

struct tPRSTAT_GroupB_Button_A_C_HANS
{
	int STATE;
	int MODE;
	double var_1;
};

union tSTATUS_GroupB_Button_A_C_HANS
{
	struct tPRSTAT_GroupB_Button_A_C_HANS write_access_;
	struct tPRSTAT_GroupB_Button_A_C_HANS read_access_;
};

/* Types for Process GroupB_Lamp_A_C */

struct tPRSTAT_GroupB_Lamp_A_C_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupB_Lamp_A_C_HANS
{
	struct tPRSTAT_GroupB_Lamp_A_C_HANS write_access_;
	struct tPRSTAT_GroupB_Lamp_A_C_HANS read_access_;
};

struct tPRINST_GroupB_Lamp_A_C_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupB_Button_A_B_C1 */

struct tPRSTAT_GroupB_Button_A_B_C1_HANS
{
	int STATE;
	int MODE;
	double var_1;
};

union tSTATUS_GroupB_Button_A_B_C1_HANS
{
	struct tPRSTAT_GroupB_Button_A_B_C1_HANS write_access_;
	struct tPRSTAT_GroupB_Button_A_B_C1_HANS read_access_;
};

/* Types for Process GroupB_Lamp_A_B_C1 */

struct tPRSTAT_GroupB_Lamp_A_B_C1_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupB_Lamp_A_B_C1_HANS
{
	struct tPRSTAT_GroupB_Lamp_A_B_C1_HANS write_access_;
	struct tPRSTAT_GroupB_Lamp_A_B_C1_HANS read_access_;
};

struct tPRINST_GroupB_Lamp_A_B_C1_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

/* Types for Process GroupB_Button_A_B_C2 */

struct tPRSTAT_GroupB_Button_A_B_C2_HANS
{
	int STATE;
	int MODE;
	double var_1;
};

union tSTATUS_GroupB_Button_A_B_C2_HANS
{
	struct tPRSTAT_GroupB_Button_A_B_C2_HANS write_access_;
	struct tPRSTAT_GroupB_Button_A_B_C2_HANS read_access_;
};

/* Types for Process GroupB_Lamp_A_B_C2 */

struct tPRSTAT_GroupB_Lamp_A_B_C2_HANS
{
	int STATE;
	int MODE;
};

union tSTATUS_GroupB_Lamp_A_B_C2_HANS
{
	struct tPRSTAT_GroupB_Lamp_A_B_C2_HANS write_access_;
	struct tPRSTAT_GroupB_Lamp_A_B_C2_HANS read_access_;
};

struct tPRINST_GroupB_Lamp_A_B_C2_HANS
{
	struct tTMEL_mLampUnit_HANS timer_;
	struct tTMQE_mLampUnit_HANS timeup_;
};

#endif // _mLampUnit_hLampUnit_HANS_

/*********************************************************************
	End of Header File for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413b-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,0X50r7qY3CMGghbsTkmY6I7rLiQ=] */
