/*********************************************************************
	SYSTEM ClusterGroup_System_Library
	IMPLEMENTATION LampImpl
	Module for CIP SHELL sLampUnit
	Filename: sLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "sLampUnit.h"

/* Input Interface */

struct tIN_LampUnit_HANS IN_LampUnit_HANS;

/* Output Interface */

struct tOUT_LampUnit_HANS OUT_LampUnit_HANS;

/* Trigger Interface */

struct tTRG_LampUnit_HANS TRG_LampUnit_HANS;

/*********************************************************************
	End of Module for CIP SHELL sLampUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,8417413b-b789-11ea-9e22-1112d6355503,HnQ4IQO9GZSh7octYiHPReGZmBg=] */
