/*********************************************************************
	SYSTEM ClusterGroup_System_Library
	IMPLEMENTATION LampImpl
	Header File for CIP SHELL sLampUnit
	Filename: sLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

#if !defined(_sLampUnit_hLampUnit_HANS_)
	#define _sLampUnit_hLampUnit_HANS_
/* Library include text */

#include <CipSystem_DatatypeLibrary>
#include <Supper_DatatypeLibrary>
#include <Group_DatatypeLibrary>

/* Code Option Constants */

#if defined(_EINPUT__)
	#undef _EINPUT__
#endif 

#if defined(_PENDING__)
	#undef _PENDING__
#endif 

/* Channel Enumerations */

#if !defined(_eCHAN_LampUnit_HANS_)
	#define _eCHAN_LampUnit_HANS_

	enum eCHAN_LampUnit_HANS
		{C_ButtonEvents = 2, C_ButtonEvents2 = 6, C_ButtonEvents3 = 4, 
		 C_ButtonEvents4 = 8, C_ButtonEvents5 = 10, C_ButtonEvents6 = 12, 
		 C_ButtonEvents7 = 14, C_ButtonEvents8 = 16, C_ButtonEvents9 = 18, 
		 C_LampActions = 1, C_LampActions2 = 5, C_LampActions3 = 3, C_LampActions4 = 7, 
		 C_LampActions5 = 9, C_LampActions6 = 11, C_LampActions7 = 13, 
		 C_LampActions8 = 15, C_LampActions9 = 17};

#endif // _eCHAN_LampUnit_HANS_

/*********************************************************************
	CODE  GENERATION  FEATURE
	This global message enumeration can be used 
	for implementation purposes.
*********************************************************************/

enum eMSG_LampUnitLampUnit_HANS
	{F_C2_Push_ = 1, F_C2_Release_ = 2, F_C4_Push_ = 3, F_C4_Release_ = 4, 
	 F_C6_Push_ = 5, F_C6_Release_ = 6, F_C8_Push_ = 7, F_C8_Release_ = 8, 
	 F_C10_Push_ = 9, F_C10_Release_ = 10, F_C12_Push_ = 11, F_C12_Release_ = 12, 
	 F_C14_Push_ = 13, F_C14_Release_ = 14, F_C16_Push_ = 15, F_C16_Release_ = 16, 
	 F_C18_Push_ = 17, F_C18_Release_ = 18, F_C1_Bright_ = 19, F_C1_Dark_ = 20, 
	 F_C3_Bright_ = 21, F_C3_Dark_ = 22, F_C5_Bright_ = 23, F_C5_Dark_ = 24, 
	 F_C7_Bright_ = 25, F_C7_Dark_ = 26, F_C9_Bright_ = 27, F_C9_Dark_ = 28, 
	 F_C11_Bright_ = 29, F_C11_Dark_ = 30, F_C13_Bright_ = 31, F_C13_Dark_ = 32, 
	 F_C15_Bright_ = 33, F_C15_Dark_ = 34, F_C17_Bright_ = 35, F_C17_Dark_ = 36};

/********************************************************************/

#if !defined(_eMSG_LampActions_HANS_)
	#define _eMSG_LampActions_HANS_

	enum eMSG_LampActions_HANS
		{C1_Bright = 1, C1_Dark = 2};

#endif // _eMSG_LampActions_HANS_

#if !defined(_eMSG_ButtonEvents_HANS_)
	#define _eMSG_ButtonEvents_HANS_

	enum eMSG_ButtonEvents_HANS
		{C2_Push = 1, C2_Release = 2};

#endif // _eMSG_ButtonEvents_HANS_

#if !defined(_eMSG_LampActions3_HANS_)
	#define _eMSG_LampActions3_HANS_

	enum eMSG_LampActions3_HANS
		{C3_Bright = 1, C3_Dark = 2};

#endif // _eMSG_LampActions3_HANS_

#if !defined(_eMSG_ButtonEvents3_HANS_)
	#define _eMSG_ButtonEvents3_HANS_

	enum eMSG_ButtonEvents3_HANS
		{C4_Push = 1, C4_Release = 2};

#endif // _eMSG_ButtonEvents3_HANS_

#if !defined(_eMSG_LampActions2_HANS_)
	#define _eMSG_LampActions2_HANS_

	enum eMSG_LampActions2_HANS
		{C5_Bright = 1, C5_Dark = 2};

#endif // _eMSG_LampActions2_HANS_

#if !defined(_eMSG_ButtonEvents2_HANS_)
	#define _eMSG_ButtonEvents2_HANS_

	enum eMSG_ButtonEvents2_HANS
		{C6_Push = 1, C6_Release = 2};

#endif // _eMSG_ButtonEvents2_HANS_

#if !defined(_eMSG_LampActions4_HANS_)
	#define _eMSG_LampActions4_HANS_

	enum eMSG_LampActions4_HANS
		{C7_Bright = 1, C7_Dark = 2};

#endif // _eMSG_LampActions4_HANS_

#if !defined(_eMSG_ButtonEvents4_HANS_)
	#define _eMSG_ButtonEvents4_HANS_

	enum eMSG_ButtonEvents4_HANS
		{C8_Push = 1, C8_Release = 2};

#endif // _eMSG_ButtonEvents4_HANS_

#if !defined(_eMSG_LampActions5_HANS_)
	#define _eMSG_LampActions5_HANS_

	enum eMSG_LampActions5_HANS
		{C9_Bright = 1, C9_Dark = 2};

#endif // _eMSG_LampActions5_HANS_

#if !defined(_eMSG_ButtonEvents5_HANS_)
	#define _eMSG_ButtonEvents5_HANS_

	enum eMSG_ButtonEvents5_HANS
		{C10_Push = 1, C10_Release = 2};

#endif // _eMSG_ButtonEvents5_HANS_

#if !defined(_eMSG_LampActions6_HANS_)
	#define _eMSG_LampActions6_HANS_

	enum eMSG_LampActions6_HANS
		{C11_Bright = 1, C11_Dark = 2};

#endif // _eMSG_LampActions6_HANS_

#if !defined(_eMSG_ButtonEvents6_HANS_)
	#define _eMSG_ButtonEvents6_HANS_

	enum eMSG_ButtonEvents6_HANS
		{C12_Push = 1, C12_Release = 2};

#endif // _eMSG_ButtonEvents6_HANS_

#if !defined(_eMSG_LampActions7_HANS_)
	#define _eMSG_LampActions7_HANS_

	enum eMSG_LampActions7_HANS
		{C13_Bright = 1, C13_Dark = 2};

#endif // _eMSG_LampActions7_HANS_

#if !defined(_eMSG_ButtonEvents7_HANS_)
	#define _eMSG_ButtonEvents7_HANS_

	enum eMSG_ButtonEvents7_HANS
		{C14_Push = 1, C14_Release = 2};

#endif // _eMSG_ButtonEvents7_HANS_

#if !defined(_eMSG_LampActions8_HANS_)
	#define _eMSG_LampActions8_HANS_

	enum eMSG_LampActions8_HANS
		{C15_Bright = 1, C15_Dark = 2};

#endif // _eMSG_LampActions8_HANS_

#if !defined(_eMSG_ButtonEvents8_HANS_)
	#define _eMSG_ButtonEvents8_HANS_

	enum eMSG_ButtonEvents8_HANS
		{C16_Push = 1, C16_Release = 2};

#endif // _eMSG_ButtonEvents8_HANS_

#if !defined(_eMSG_LampActions9_HANS_)
	#define _eMSG_LampActions9_HANS_

	enum eMSG_LampActions9_HANS
		{C17_Bright = 1, C17_Dark = 2};

#endif // _eMSG_LampActions9_HANS_

#if !defined(_eMSG_ButtonEvents9_HANS_)
	#define _eMSG_ButtonEvents9_HANS_

	enum eMSG_ButtonEvents9_HANS
		{C18_Push = 1, C18_Release = 2};

#endif // _eMSG_ButtonEvents9_HANS_

/* Input Interface Type */

struct tIN_LampUnit_HANS
{
	void (*ButtonEvents) (enum eMSG_ButtonEvents_HANS);
	void (*ButtonEvents2) (enum eMSG_ButtonEvents2_HANS);
	void (*ButtonEvents3) (enum eMSG_ButtonEvents3_HANS);
	void (*ButtonEvents4) (enum eMSG_ButtonEvents4_HANS);
	void (*ButtonEvents5) (enum eMSG_ButtonEvents5_HANS);
	void (*ButtonEvents6) (enum eMSG_ButtonEvents6_HANS);
	void (*ButtonEvents7) (enum eMSG_ButtonEvents7_HANS);
	void (*ButtonEvents8) (enum eMSG_ButtonEvents8_HANS);
	void (*ButtonEvents9) (enum eMSG_ButtonEvents9_HANS);
};

/* Output Interface Type */

struct tOUT_LampUnit_HANS
{
	void (*LampActions) (enum eMSG_LampActions_HANS);
	void (*LampActions2) (enum eMSG_LampActions2_HANS);
	void (*LampActions3) (enum eMSG_LampActions3_HANS);
	void (*LampActions4) (enum eMSG_LampActions4_HANS);
	void (*LampActions5) (enum eMSG_LampActions5_HANS);
	void (*LampActions6) (enum eMSG_LampActions6_HANS);
	void (*LampActions7) (enum eMSG_LampActions7_HANS);
	void (*LampActions8) (enum eMSG_LampActions8_HANS);
	void (*LampActions9) (enum eMSG_LampActions9_HANS);
};


/* Trigger Interface Type */

struct tTRG_LampUnit_HANS
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/*  trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
};

/* External Interface Declarations */

extern struct tIN_LampUnit_HANS IN_LampUnit_HANS;		/* Input Channel Interface defined in sLampUnit.c */
extern struct tOUT_LampUnit_HANS OUT_LampUnit_HANS;		/* Output Channel Interface defined in sLampUnit.c */
extern struct tTRG_LampUnit_HANS TRG_LampUnit_HANS;		/* Trigger Interface defined in sLampUnit.c */

/* Unit Initialization Function, defined in mLampUnit.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_LampUnit_HANS(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iCHAN_LampUnit_HANS(void);

#endif // _sLampUnit_hLampUnit_HANS_

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[b7934a9b-259a-11e1-ae2f-a14f3e396de6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,8417413b-b789-11ea-9e22-1112d6355503,a9OFf60ILrqeHfFUzti0dh7JcAw=] */
