/*********************************************************************
	SYSTEM ClusterGroup_System_Library
	IMPLEMENTATION LampImpl
	Trace Interface Module for CIP MACHINE mLampUnit
	Filename: tLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		use postfix
			 LampUnit_HANS
		enable mode inspection
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "tLampUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,8417413c-b789-11ea-9e22-1112d6355503,841740f2-b789-11ea-9e22-1112d6355503,841741d7-b789-11ea-9e22-1112d6355503,8417413a-b789-11ea-9e22-1112d6355503,Cx69CpVEo+lXy6iDjtti4G66Qtc=] */
